TEST: added benchmark-tests and utility functions

diff --git a/test/test_functions b/test/test_functions
--- a/test/test_functions
+++ b/test/test_functions
@@ -28,6 +28,12 @@ CVMFS_TEST_S3_CONFIG=${CVMFS_TEST_S3_CONFIG:=}
 CVMFS_TEST_STRATUM0=${CVMFS_TEST_STRATUM0:=}
 CVMFS_TEST_SERVER_CACHE=${CVMFS_TEST_SERVER_CACHE:=}
 
+CVMFS_OPT_WARM_CACHE=${CVMFS_OPT_WARM_CACHE:=yes}
+CVMFS_OPT_ITERATIONS=${CVMFS_OPT_ITERATIONS:=1}
+CVMFS_OPT_TEST_TYPE=${CVMFS_OPT_TEST_TYPE:=callgrind} # callgrind / memcheck
+CVMFS_OPT_CONFIG_FILE=${CVMFS_OPT_CONFIG_FILE:=}
+CVMFS_OPT_OUTPUT_DIR=${CVMFS_OPT_OUTPUT_DIR:=~/cvmfs_benchmarks}
+
 die() {
   echo -e $1 >&2
   exit 1
@@ -1180,4 +1186,115 @@ cp_usrbin() {
   for f in $(find $destination_directory -type f); do
     sudo chmod 0444 $f || return 3
   done
+}
+
+
+# waits until cvmfs is mounted
+wait_fqrn_mount() {
+  local waits=0
+  while ! mount | grep "/cvmfs/${FQRN}" > /dev/null; do
+    waits=$(( waits + 1 ))
+    if [ "$waits" -ge 10 ]; then
+      echo "${FQRN} could not be mounted (not superuser?)"
+      exit -1
+    fi
+    sleep 1
+  done
+}
+
+
+# runs the command once in order to get a warm cache
+create_warm_cache() {
+  cvmfs2 -f -o config=cvmfs.conf,disable_watchdog,simple_options_parsing $FQRN /cvmfs/$FQRN &> /dev/null &
+  wait_fqrn_mount
+  echo -e $COMMAND | bash &> /dev/null
+  umount /cvmfs/$FQRN
+}
+
+
+# creates the default cvmfs.conf file for normal testing
+#
+# @param destination_file  absolute path of the directory
+create_default_cvmfs_config() {
+  local destination_directory="$1"
+  echo 'CVMFS_CACHE_BASE=/root/cvmfs_testing/cache
+CVMFS_RELOAD_SOCKETS=/root/cvmfs_testing/cache
+CVMFS_SERVER_URL=http://cvmfs-stratum-one.cern.ch/cvmfs/@fqrn@
+CVMFS_SHARED_CACHE=no
+CVMFS_HTTP_PROXY=http://ca-proxy.cern.ch:3128
+CVMFS_AUTO_UPDATE=false' > $destination_directory/cvmfs.conf
+}
+
+
+# sets the valgrind options depending on the test type
+#
+# @param test_type  concrete test to execute
+set_valgrind_options() {
+  local CVMFS_OPT_CALLGRIND="--tool=callgrind --dump-before=fuse_session_loop_mt --dump-after=fuse_session_loop_mt --dsymutil=yes --log-file=${FQRN}.callgrind.log -v"
+  local CVMFS_OPT_MEMCHECK="--tool=memcheck --xml=yes --xml-file=${FQRN}.memcheck.xml --trace-children=yes --child-silent-after-fork=yes --leak-check=yes --log-file=${FQRN}.memcheck.log -v"
+  OPTIONS=""
+  case $CVMFS_OPT_TEST_TYPE in
+    callgrind)
+      OPTIONS=$CVMFS_OPT_CALLGRIND
+    ;;
+    memcheck)
+      OPTIONS=$CVMFS_OPT_MEMCHECK
+    ;;
+  esac
+}
+
+
+# creates the environment to run the benchmark
+#
+# @param workspace  absolute path to the directory where the benchmark will put the files in
+setup_benchmark_environment() {
+  local workspace="$1"
+  mkdir -p /cvmfs/$FQRN
+  mkdir -p $CVMFS_OPT_OUTPUT_DIR/$FQRN
+  mkdir -p $workspace/cache
+
+  # stopping automount
+  service autofs stop &> /dev/null
+
+  # create a cvmfs.conf file or use a custom one
+  if [ -z $CVMFS_OPT_CONFIG_FILE ]; then
+    create_default_cvmfs_config $workspace
+  else
+    cp -f $CVMFS_OPT_CONFIG_FILE $workspace
+  fi
+}
+
+
+# runs a benchmark $CVMFS_OPT_ITERATIONS times
+run_benchmark() {
+  local count=$CVMFS_OPT_ITERATIONS
+  set_valgrind_options
+
+  echo "Starting loading the profiler and mounting in /cvmfs/${FQRN}"
+  echo "Running valgrind with the following parameters: $OPTIONS"
+  echo "Launching the job $count times"
+  valgrind $OPTIONS cvmfs2 -f -o config=cvmfs.conf,disable_watchdog,simple_options_parsing $FQRN /cvmfs/$FQRN &
+  PID=$!
+  wait_fqrn_mount
+
+  local iteration=1
+  while (( count > 0 )); do
+    echo "Starting iteration ${iteration}"
+    echo -e $COMMAND | bash &> /dev/null
+    count=$(( count - 1 ))
+    iteration=$(( iteration + 1 ))
+  done
+
+  echo "Iterations finished. Unmounting cvmfs"
+
+  umount /cvmfs/$FQRN
+  wait $PID
+}
+
+
+# collects the files and pastes them into $CVMFS_OPT_OUTPUT_DIR/$FQRN
+collect_benchmark_results() {
+  local benchmark_output_dir="$CVMFS_OPT_OUTPUT_DIR/$FQRN"
+  rm -rf $benchmark_output_dir/*
+  cp  -rf $FQRN.*.log callgrind.out.* $FQRN.memcheck.xml cvmfs.conf $benchmark_output_dir &>/dev/null
 }
