Avoid deadlocks in notification system integration test

diff --git a/test/src/900-notification_system/main b/test/src/900-notification_system/main
--- a/test/src/900-notification_system/main
+++ b/test/src/900-notification_system/main
@@ -9,8 +9,6 @@ clean_up() {
 }
 
 publish_and_notify() {
-    sleep 1
-
     sudo cvmfs_server transaction $CVMFS_TEST_REPO
     echo "Test" > /cvmfs/$CVMFS_TEST_REPO/marker.txt
     sudo cvmfs_server publish $CVMFS_TEST_REPO
@@ -25,17 +23,22 @@ run_tests() {
 
     create_empty_repo $CVMFS_TEST_REPO $CVMFS_TEST_USER || return $?
 
-    publish_and_notify &
+    publish_and_notify
 
-    # Run the subscriber tool which blocks until a notification is received
-    echo "Wait for notification that repository is at revision > 2"
+    if [ "x$?" != "x0" ]; then
+        echo "Could not publish manifest to notification server"
+        return 1
+    fi
+
+    # Run the subscriber tool
     local rev1=$(cvmfs_swissknife notify -s \
         -u $NOTIFICATION_SERVER_URL/subscribe \
-        -t $CVMFS_TEST_REPO -m 2 | awk '{print $NF}' | cut -c1)
+        -t $CVMFS_TEST_REPO | awk '{print $NF}' | cut -c1)
+    echo "Repository is now at revision: $rev1"
 
     if [ $((rev1)) -lt 3 ]; then
         echo "Repository revision $rev should be > 2"
-        return 1
+        return 2
     fi
 }
 
