add test for looking at file before kcache timeout

diff --git a/test/src/611-idleclient/main b/test/src/611-idleclient/main
--- a/test/src/611-idleclient/main
+++ b/test/src/611-idleclient/main
@@ -91,6 +91,23 @@ cvmfs_run_test() {
     return 21
   fi
 
+  echo "starting transaction to update repository again"
+  start_transaction $CVMFS_TEST_REPO || return $?
+
+  echo "add another new file"
+  touch $repo_dir/newfile || return 31
+
+  echo "attempt to access the file before publishing, expect missing"
+  stat $TEST_611_MOUNTPOINT/newfile && return 32
+
+  echo "creating CVMFS snapshot"
+  publish_repo $CVMFS_TEST_REPO || return $?
+
+  sleep_time=3
+  echo "sleeping $sleep_time seconds to let ttl expire but not kernel cache"
+  ls -l $TEST_611_MOUNTPOINT || return 33
+  stat $TEST_611_MOUNTPOINT/newfile || return 34
+
   return 0
 }
 
