TEST: test 630 tests `cvmfs_server mount -a`

diff --git a/test/src/630-servermount/main b/test/src/630-servermount/main
--- a/test/src/630-servermount/main
+++ b/test/src/630-servermount/main
@@ -25,6 +25,14 @@ enable_auto_repair() {
   set_auto_repair $name "true"
 }
 
+CVMFS_TEST_630_REPLICA_NAME=
+CVMFS_TEST_630_REPO2_NAME=
+cleanup() {
+  echo "running cleanup()..."
+  [ -z $CVMFS_TEST_630_REPLICA_NAME ] || sudo cvmfs_server rmfs -f $CVMFS_TEST_630_REPLICA_NAME
+  [ -z $CVMFS_TEST_630_REPO2_NAME   ] || sudo cvmfs_server rmfs -f $CVMFS_TEST_630_REPO2_NAME
+}
+
 cvmfs_run_test() {
   logfile=$1
   local repo_dir=/cvmfs/$CVMFS_TEST_REPO
@@ -144,6 +152,103 @@ cvmfs_run_test() {
 
   echo "set CVMFS_AUTO_REPAIR_MOUNTPOINT=true"
   enable_auto_repair $CVMFS_TEST_REPO || return 39
+
+  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
+  # Create more repositories and Stratum1s to check `cvmfs_server mount -a`
+
+  echo "install a cleanup function"
+  trap cleanup EXIT HUP INT TERM
+
+  echo "create Stratum1 repository on the same machine"
+  load_repo_config $CVMFS_TEST_REPO
+  local replica_name="$(get_stratum1_name $CVMFS_TEST_REPO)"
+  CVMFS_TEST_630_REPLICA_NAME=$replica_name
+  create_stratum1 $replica_name                          \
+                  $CVMFS_TEST_USER                       \
+                  $CVMFS_STRATUM0                        \
+                  /etc/cvmfs/keys/${CVMFS_TEST_REPO}.pub || return 40
+
+  echo "initial snapshot into $replica_name"
+  cvmfs_server snapshot $replica_name || return 41
+
+  local repo2="${CVMFS_TEST_REPO}.$(date +%s%N | sha1sum | head -c6)"
+  echo "create a second Stratum0 ($repo2) owned by $CVMFS_TEST_USER"
+  CVMFS_TEST_630_REPO2_NAME=$repo2
+  create_repo $repo2 $CVMFS_TEST_USER || return 42
+
+  echo "pull in repository configuration for $repo2"
+  load_repo_config $repo2 || return 43
+  local repo2_repo_dir="/cvmfs/${repo2}"
+  local repo2_rdonly_dir="${CVMFS_SPOOL_DIR}/rdonly"
+
+  echo -n "check if there are more repositories than expected... "
+  local repo_count=$(cvmfs_server list | wc -l)
+  if [ $repo_count -eq 3 ]; then
+    echo "no"
+  else
+    echo "yes ($repo_count repos found)"
+    cvmfs_server list
+    echo "WARNING: THIS MIGHT AFFECT THE OUTCOME OF THE NEXT TESTS..."
+    CVMFS_GENERAL_WARNING_FLAG=1
+  fi
+
+  echo "Check that the repositories are properly mounted"
+  cat /proc/mounts | grep -e " $repo_dir "         || return 44
+  cat /proc/mounts | grep -e " $rdonly_dir "       || return 45
+  cat /proc/mounts | grep -e " $repo2_repo_dir "   || return 46
+  cat /proc/mounts | grep -e " $repo2_rdonly_dir " || return 47
+
+  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
+  # Run `cvmfs_server mount -a` with all repos properly mounted
+
+  if [ x"$(whoami)" != x"root" ]; then
+    local mount_log_1="$(pwd)/mount_1.log"
+    echo "run \`cvmfs_server mount -a\` without necessity and as non-root (log: $mount_log_1)"
+    cvmfs_server mount -a > $mount_log_1 2>&1 && return 48
+
+    echo "check error message"
+    cat $mount_log_1 | grep 'need root to mount all' || return 49
+  else
+    echo "WARNING: cannot test non-root behaviour of \`cvmfs_server mount -a\` as root"
+    CVMFS_GENERAL_WARNING_FLAG=1
+  fi
+
+  echo "do \`cvmfs_server mount -a\` without necessity"
+  sudo cvmfs_server mount -a || return 50
+
+  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
+  # Run `cvmfs_server mount -a` with mount problems in the repositories
+
+  echo "break mounts for the repositories (umount rdonly for $CVMFS_TEST_REPO)"
+  cvmfs_suid_helper rw_umount     $CVMFS_TEST_REPO || return 51
+  cvmfs_suid_helper rdonly_umount $CVMFS_TEST_REPO || return 52
+  cvmfs_suid_helper rw_mount      $CVMFS_TEST_REPO || return 53
+
+  echo "open transaction for $repo2"
+  start_transaction $repo2 || return 54
+
+  echo "break mounts for the repositories (umount rdonly for $repo2 and make union read-only)"
+  cvmfs_suid_helper rw_umount     $repo2 || return 55
+  cvmfs_suid_helper rdonly_umount $repo2 || return 56
+  cvmfs_suid_helper rw_mount      $repo2 || return 57
+
+  echo "Check that the repositories are not properly mounted"
+  cat /proc/mounts | grep -e " $repo_dir "         || return 58
+  cat /proc/mounts | grep -e " $rdonly_dir "       && return 59
+  cat /proc/mounts | grep -e " $repo2_repo_dir "   || return 60
+  cat /proc/mounts | grep -e " $repo2_rdonly_dir " && return 61
+
+  echo "do \`cvmfs_server mount -a\` to bring all repositories back into proper shape"
+  sudo cvmfs_server mount -a || return 62
+
+  echo "Check that the repositories are properly mounted"
+  cat /proc/mounts | grep -e " $repo_dir "         || return 63
+  cat /proc/mounts | grep -e " $rdonly_dir "       || return 64
+  cat /proc/mounts | grep -e " $repo2_repo_dir "   || return 65
+  cat /proc/mounts | grep -e " $repo2_rdonly_dir " || return 66
+
+  echo "publish $repo2"
+  publish_repo $repo2 || return 67
 
   return 0
 }
