remove fine grained log file redirection in tests

diff --git a/test/src/525-bigrepo/main b/test/src/525-bigrepo/main
--- a/test/src/525-bigrepo/main
+++ b/test/src/525-bigrepo/main
@@ -8,58 +8,58 @@ cvmfs_run_test() {
 
   local scratch_dir=$(pwd)
 
-  echo "create a fresh repository named $CVMFS_TEST_REPO with user $CVMFS_TEST_USER" >> $logfile
-  create_empty_repo $CVMFS_TEST_REPO $CVMFS_TEST_USER >> $logfile 2>&1 || return $?
+  echo "create a fresh repository named $CVMFS_TEST_REPO with user $CVMFS_TEST_USER"
+  create_empty_repo $CVMFS_TEST_REPO $CVMFS_TEST_USER || return $?
 
-  echo "starting transaction to edit repository" >> $logfile
-  start_transaction $CVMFS_TEST_REPO >> $logfile 2>&1 || return $?
+  echo "starting transaction to edit repository"
+  start_transaction $CVMFS_TEST_REPO || return $?
 
-  echo "generating an artificial but more or less representative repo" >> $logfile
-  make_huge_repo $repo_dir >> $logfile 2>&1 || return 1
+  echo "generating an artificial but more or less representative repo"
+  make_huge_repo $repo_dir || return 1
 
-  echo "creating CVMFS snapshot" >> $logfile
-  publish_repo $CVMFS_TEST_REPO >> $logfile 2>&1 || return $?
+  echo "creating CVMFS snapshot"
+  publish_repo $CVMFS_TEST_REPO || return $?
 
-  echo "check catalog integrity" >> $logfile
-  check_catalogs $CVMFS_TEST_REPO >> $logfile 2>&1 || return $?
+  echo "check catalog integrity"
+  check_catalogs $CVMFS_TEST_REPO || return $?
 
-  echo "find out how many file system items are in the repo" >> $logfile
+  echo "find out how many file system items are in the repo"
   local num_1
   num_1=$(find $repo_dir | wc -l 2>>$logfile)
-  echo "found $num_1 file system entries" >> $logfile
+  echo "found $num_1 file system entries"
 
-  echo "starting a new transaction" >> $logfile
-  start_transaction $CVMFS_TEST_REPO >> $logfile 2>&1 || return $?
+  echo "starting a new transaction"
+  start_transaction $CVMFS_TEST_REPO || return $?
 
-  echo "creating nested catalog markers" >> $logfile
+  echo "creating nested catalog markers"
   local num_nested_catalogs=0
   for dir in $(find $repo_dir -maxdepth 1 -mindepth 1 -type d); do
-    touch $dir/.cvmfscatalog >> $logfile 2>&1 || return $?
+    touch $dir/.cvmfscatalog || return $?
     num_nested_catalogs=$(( $num_nested_catalogs + 1 ))
   done
-  echo "generated $num_nested_catalogs catalogs" >> $logfile
+  echo "generated $num_nested_catalogs catalogs"
 
-  echo "creating nested catalogs by cvmfs_server publish" >> $logfile
-  publish_repo $CVMFS_TEST_REPO >> $logfile 2>&1 || return $?
+  echo "creating nested catalogs by cvmfs_server publish"
+  publish_repo $CVMFS_TEST_REPO || return $?
 
-  echo "check catalog integrity" >> $logfile
-  check_catalogs $CVMFS_TEST_REPO >> $logfile 2>&1 || return $?
+  echo "check catalog integrity"
+  check_catalogs $CVMFS_TEST_REPO || return $?
 
-  echo "check if all nested catalogs are present" >> $logfile
+  echo "check if all nested catalogs are present"
   for dir in $(find $repo_dir -maxdepth 1 -mindepth 1 -type d); do
     local nested_root
     nested_root=$(basename $dir)
-    echo -n "checking: /$nested_root ... " >> $logfile
-    check_catalog_presence "/$nested_root" $CVMFS_TEST_REPO >> $logfile 2>&1 || { echo "not found" >> $logfile; return 2; }
-    echo "found" >> $logfile
+    echo -n "checking: /$nested_root ... "
+    check_catalog_presence "/$nested_root" $CVMFS_TEST_REPO || { echo "not found"; return 2; }
+    echo "found"
   done
 
-  echo "check again for the number of file system entries" >> $logfile
+  echo "check again for the number of file system entries"
   local num_2
   num_2=$(find $repo_dir | wc -l 2>>$logfile)
-  echo "found $num_2 file system entries" >> $logfile
+  echo "found $num_2 file system entries"
 
-  echo "check if file system entries match" >> $logfile
+  echo "check if file system entries match"
   local num_diff
   num_diff=$(( $num_2 - $num_1 ))
   if [ $num_diff -ne $num_nested_catalogs ]; then
