Update integration test

diff --git a/test/src/081-shrinkwrap/main b/test/src/081-shrinkwrap/main
--- a/test/src/081-shrinkwrap/main
+++ b/test/src/081-shrinkwrap/main
@@ -5,8 +5,40 @@ cvmfs_test_name="shrinkwrap"
 cleanup() {
     sudo rm -f /tmp/cvmfs-$repo.trace.log 2> /dev/null
     sudo rm -f /tmp/cvmfs-$repo.spec.txt  2> /dev/null
-    sudo rm -f /tmp/cvmfs  2> /dev/null
+ 
+    sudo rm -rf /tmp/cvmfs 2> /dev/null
+    sudo rm -rf /var/lib/cvmfs/shrinkwrap 2> /dev/null
+    sudo umount /cvmfs/ 2> /dev/null
 }
+
+redun_umount() {
+  local repositories=$1
+  local times=5
+  local result=-1
+
+  for r in $(echo $repositories | tr , " "); do
+    while (( result != 0 && times > 0  )); do
+      sudo umount $r > /dev/null 2>&1
+      result=$?
+      times=$(( $times - 1 ))
+      if [ $result -ne 0 ] && [ $times -gt 0 ]; then
+        echo "Failed to umount. Trying again..." $r
+        sleep 1
+      fi
+    done
+
+    if [ $result -ne 0 ]; then
+      lsof | grep $r 
+      return 200
+    fi
+
+    times=5
+    result=-1
+  done
+
+  return 0
+}
+
 
 cvmfs_run_test() {
     logfile=$1
@@ -40,29 +72,46 @@ cvmfs_run_test() {
     echo "*** Creating specification file..."
 
     sudo python $TEST_ROOT/../add-ons/export_plugin/spec_builder.py /tmp/cvmfs-$repo.trace.log /tmp/cvmfs-$repo.spec.txt
+    result=$?
+
+    if [[ $result != 0 ]]; then
+      echo "*** ERROR: failed to create specification : " $result
+      return 3
+    fi
+
 
     echo "*** Creating shrinkwrapped repository..."
 
     sudo cvmfs_shrinkwrap -r $repo -f $TEST_ROOT/src/081-shrinkwrap/$repo.config -t /tmp/cvmfs-$repo.spec.txt
+    result=$?
 
-    if [[ $? != 0 ]]; then
-      echo "*** ERROR: failed to create shrinkwrapped repository : " $?
-      return 3
+    if [[ $result != 0 ]]; then
+      echo "*** ERROR: failed to create shrinkwrapped repository : " $result
+      return 4
+    fi
+
+    # This is verifies the file exists, but was not part of the spec.
+    # this is used later to verify the creation and mount were successful.
+    ls /cvmfs/sft.cern.ch/lcg/mapfile.txt
+    result=$?
+
+    if [[ $result != 0 ]]; then
+      echo "*** ERROR: /cvmfs/sft.cern.ch/lcg/mapfile.txt should be present : " $result
+      return 5
     fi
 
     echo "*** Unmount CMVFS and remount recreated repo..."
 
     sudo service autofs stop
 
-    sleep 5
+    sudo mkdir -p /cvmfs/
+    sudo mount --bind /tmp/cvmfs/ /cvmfs/
+    result=$?
 
-    cvmfs_umount $repo
-
-    sleep 5
-    sudo mkdir -p /cvmfs
-    sudo mount --bind /tmp/cvmfs /cvmfs
-
-    sleep 5
+    if [[ $result != 0 ]]; then
+      echo "*** ERROR: failed to mount repository : " $result
+      return 6
+    fi
 
     echo "*** Try same steps as before used to create specification..."
 
@@ -71,12 +120,36 @@ cvmfs_run_test() {
     . /cvmfs/sft.cern.ch/lcg/releases/ROOT/6.10.04-4c60e/x86_64-centos7-gcc7-opt/bin/thisroot.sh
 
     root -h
+    result=$?
+
+    # root returns 1 for with -h option
+    if [[ $result != 1 ]]; then
+      echo "*** ERROR: root failed to run : " $result
+      return 7
+    fi
+
+
+    ls /cvmfs/sft.cern.ch/lcg/mapfile.txt
+    result=$?
+
+    if [[ $result != 2 ]]; then
+      echo "*** ERROR: file should not be present : " $result
+      return 8
+    fi
 
     echo "*** Unmount and clean repo..."
 
-    sleep 5
+    rm -rf /tmp/cvmfs
+    rm -rf /var/lib/cvmfs/shrinkwrap
 
-    sudo umount /cvmfs
+    redun_umount /cvmfs/
+    result=$?
+
+    if [[ $result != 0 ]]; then
+      echo "*** ERROR: failed to mount repository : " $result
+      return 9
+    fi
+
 
     return 0
 }
