cache proxy settings in workspace directory

diff --git a/test/src/031-cacheautoproxy/main b/test/src/031-cacheautoproxy/main
--- a/test/src/031-cacheautoproxy/main
+++ b/test/src/031-cacheautoproxy/main
@@ -15,7 +15,17 @@ EOF
   cvmfs_mount grid.cern.ch || return 11
   cvmfs_umount grid.cern.ch || return 12
 
+  echo "*** auto without network or cached proxy should fail"
   cvmfs_mount grid.cern.ch "CVMFS_HTTP_PROXY=auto" \
+    "CVMFS_EXTERNAL_HTTP_PROXY=auto" \
+    "CVMFS_PAC_URLS=file:///no/such/file" && return 13
+
+  echo "*** restarting autofs"
+  autofs_switch off || return 14
+  autofs_switch on  || return 15
+
+  cvmfs_mount grid.cern.ch "CVMFS_HTTP_PROXY=auto" \
+    "CVMFS_EXTERNAL_HTTP_PROXY=auto" \
     "CVMFS_PAC_URLS=file://$wpad_file" || return 20
   proxy="$(get_xattr proxy /cvmfs/grid.cern.ch)"
   echo "*** proxy is $proxy"
@@ -25,12 +35,40 @@ EOF
   cvmfs_umount grid.cern.ch
 
   cvmfs_mount grid.cern.ch "CVMFS_HTTP_PROXY=auto" \
+    "CVMFS_EXTERNAL_HTTP_PROXY=auto" \
     "CVMFS_PAC_URLS=file:///no/such/file" || return 30
   proxy="$(get_xattr proxy /cvmfs/grid.cern.ch)"
   echo "*** proxy is $proxy"
   if [ x"$proxy" != x"http://no-such-proxy.cern.ch:3128" ]; then
     return 31
   fi
+  cvmfs_umount grid.cern.ch
+
+  echo "*** changing proxy settings"
+  cat > $wpad_file << EOF
+  function FindProxyForURL(url, host) {
+    return "PROXY http://no-such-other-proxy.cern.ch:3128"
+  }
+EOF
+  cvmfs_mount grid.cern.ch "CVMFS_HTTP_PROXY=auto" \
+    "CVMFS_EXTERNAL_HTTP_PROXY=auto" \
+    "CVMFS_PAC_URLS=file://$wpad_file" || return 40
+  proxy="$(get_xattr proxy /cvmfs/grid.cern.ch)"
+  echo "*** proxy is $proxy"
+  if [ x"$proxy" != x"http://no-such-other-proxy.cern.ch:3128" ]; then
+    return 41
+  fi
+  cvmfs_umount grid.cern.ch
+
+  cvmfs_mount grid.cern.ch "CVMFS_HTTP_PROXY=auto" \
+    "CVMFS_EXTERNAL_HTTP_PROXY=auto" \
+    "CVMFS_PAC_URLS=file:///no/such/file" || return 50
+  proxy="$(get_xattr proxy /cvmfs/grid.cern.ch)"
+  echo "*** proxy is $proxy"
+  if [ x"$proxy" != x"http://no-such-other-proxy.cern.ch:3128" ]; then
+    return 51
+  fi
+
 
   return 0
 }
