all change requests but return type of GetValue ("ENOENT")

diff --git a/test/src/087-xattrs/main b/test/src/087-xattrs/main
--- a/test/src/087-xattrs/main
+++ b/test/src/087-xattrs/main
@@ -8,7 +8,7 @@ check_protected_xattr() {
   cvmfs_mount grid.cern.ch "CVMFS_MAGIC_XATTRS_VISIBILITY=always" || return 3
   local no_restrictions=$(get_xattr fqrn /cvmfs/grid.cern.ch/README)
 
-  [ "$no_restrictions" = "grid.cern.ch" ] || return 30
+  [ "$no_restrictions" = "grid.cern.ch" ] || return 60
   cvmfs_umount grid.cern.ch || return 2
   echo "  ...Success"
 
@@ -19,7 +19,7 @@ CVMFS_XATTR_PRIVILEGED_GIDS=$user_gid
 CVMFS_XATTR_PROTECTED_XATTRS=user.fqrn" || return 3
   local ok_user=$(get_xattr fqrn /cvmfs/grid.cern.ch/README)
 
-  [ "$ok_user" = "grid.cern.ch" ] || return 31
+  [ "$ok_user" = "grid.cern.ch" ] || return 61
 
   cvmfs_umount grid.cern.ch || return 2
   echo "  ...Success"
@@ -38,8 +38,8 @@ CVMFS_XATTR_PROTECTED_XATTRS=user.fqrn" || return 3
   echo "    Test non-root"
   local non_root_denied=$(get_xattr fqrn /cvmfs/grid.cern.ch/README)
 
-  [ "$root_access" = "grid.cern.ch" ] || return 32
-  [ "$non_root_denied" = "grid.cern.ch" ] && return 33
+  [ "$root_access" = "grid.cern.ch" ] || return 62
+  [ "$non_root_denied" = "grid.cern.ch" ] && return 63
 
   cvmfs_umount grid.cern.ch || return 2
   echo "  ...Success"
@@ -131,6 +131,37 @@ cvmfs_run_test() {
 
   if echo $runc_chunk_list_human | grep -v "$runc_chunk_list_machine"; then
     return 32
+  fi
+
+  echo "*** Check info elements"
+  info_human_correct="Access xattr with xattr~<page_num> (machine-readable mode) or  xattr@<page_num> (human-readable mode).
+Pages available: 1"
+  info_machine_correct="num_pages, 1"
+  info_human=$(get_xattr proxy_list@? /cvmfs/grid.cern.ch/README)
+  info_machine=$(get_xattr proxy_list~? /cvmfs/grid.cern.ch/README)
+
+  [ "x$info_human" != "$info_human_correct" ] || return 40
+  [ "x$info_machine" != "$info_machine_correct" ] || return 41
+
+  echo "*** Check invalid input for num pages"
+  negative_num=$(get_xattr proxy_list@-2 /cvmfs/grid.cern.ch/README 2>&1)
+  large_num=$(get_xattr proxy_list~1000 /cvmfs/grid.cern.ch/README 2>&1)  
+  letters_num=$(get_xattr proxy_list~xxx /cvmfs/grid.cern.ch/README 2>&1) 
+  nothing=$(get_xattr proxy_list@ /cvmfs/grid.cern.ch/README 2>&1) 
+
+  error="attr_get: No data available"
+
+  if echo $negative_num | grep -v "$error"; then
+    return 50
+  fi
+  if echo $large_num | grep -v "$error"; then
+    return 51
+  fi
+  if echo $letters_num | grep -v "$error"; then
+    return 52
+  fi
+  if echo $nothing | grep -v "$error"; then
+    return 53
   fi
 
   cvmfs_umount grid.cern.ch || return 2
