add test for ingesting tarbal in repository root

diff --git a/test/src/659-tarball_ingest_in_root/main b/test/src/659-tarball_ingest_in_root/main
--- a/test/src/659-tarball_ingest_in_root/main
+++ b/test/src/659-tarball_ingest_in_root/main
@@ -1,5 +1,5 @@
 
-cvmfs_test_name="Ingest tarball in a repo from STDIN"
+cvmfs_test_name="Ingest tarball in a repository root"
 cvmfs_test_autofs_on_startup=false
 
 produce_tarball() {
@@ -31,9 +31,8 @@ cvmfs_run_test() {
   logfile=$1
   local scratch_dir=$(pwd)
   local tarfile=$scratch_dir/tarball.tar
-  local dir=tar_dir
   local repo_dir=/cvmfs/$CVMFS_TEST_REPO
-
+  
   echo "*** create a fresh repository named $CVMFS_TEST_REPO with user $CVMFS_TEST_USER"
   create_empty_repo $CVMFS_TEST_REPO $USER || return $?
 
@@ -42,100 +41,9 @@ cvmfs_run_test() {
   echo "*** generating a tarball $tarfile"
   produce_tarball $tarfile
 
-  echo "*** ingesting the tarball in the directory $dir"
-  cat $tarfile | cvmfs_server ingest --base_dir $dir --tar_file - $CVMFS_TEST_REPO || return $?
-
-  echo "*** check catalog and data integrity"
-  check_repository $CVMFS_TEST_REPO -i || return $?
-
-  if [ ! -d $repo_dir/$dir/tarball_foo ]; then
-    return 1
-  fi
-
-  for d in a a/b a/b/c; do
-    if [ ! -d $repo_dir/$dir/tarball_foo/$d ]; then
-      echo "*** Error not found directory: $repo_dir/$dir/tarball_foo/$d"
-      return 1
-    else
-      echo "*** Ingested directory: $repo_dir/$dir/tarball_foo/$d"
-
-      for f in 1 2 3; do
-        file=$repo_dir/$dir/tarball_foo/$d/$f.txt
-        if [ ! -f $file ] || [ $(wc -c <$file) -ne 2048 ]; then
-          echo "*** Error not found file: $file"
-          return 1
-        else
-          echo "*** Ingested file of size 2048 bytes: $file"
-        fi
-      done
-
-    fi
-  done
-
-  file=$repo_dir/$dir/tarball_foo/d/e/f/foo.txt
-  file_size=$(wc -c <$file)
-  if [ ! -f $file ] || [ $file_size -ne 5120 ]; then
-    echo "*** Error not found file of size 5120: $file"
-    return 1
-  else
-    echo "*** Ingested file of size $file_size bytes: $file"
-  fi
-
-  if [ $file_size -eq 5120 ]; then
-    echo "*** It compare well"
-  fi
-
-  ### Below we ingest the file with the --catalog option
-
-  echo "*** ingesting tarball when generating a catalog"
-  dir=tar_dir_with_catalog
-  cat $tarfile | cvmfs_server ingest --catalog --base_dir $dir --tar_file - $CVMFS_TEST_REPO || return $?
-
-  echo "*** check catalog and data integrity"
-  check_repository $CVMFS_TEST_REPO -i || return $?
-
-  echo "check that the catalog was created and that can be accessed"
-  cat $repo_dir/$dir/.cvmfscatalog > /dev/null || return 105
-
-  if [ ! -d $repo_dir/$dir/tarball_foo ]; then
-    return 1
-  fi
-
-  for d in a a/b a/b/c; do
-    if [ ! -d $repo_dir/$dir/tarball_foo/$d ]; then
-      echo "*** Error not found directory: $repo_dir/$dir/tarball_foo/$d"
-      return 1
-    else
-      echo "*** Ingested directory: $repo_dir/$dir/tarball_foo/$d"
-
-      for f in 1 2 3; do
-        file=$repo_dir/$dir/tarball_foo/$d/$f.txt
-        if [ ! -f $file ] || [ $(wc -c <$file) -ne 2048 ]; then
-          echo "*** Error not found file: $file"
-          return 1
-        else
-          echo "*** Ingested file of size 2048 bytes: $file"
-        fi
-      done
-
-    fi
-  done
-
-  file=$repo_dir/$dir/tarball_foo/d/e/f/foo.txt
-  file_size=$(wc -c <$file)
-  if [ ! -f $file ] || [ $file_size -ne 5120 ]; then
-    echo "*** Error not found file of size 5120: $file"
-    return 1
-  else
-    echo "*** Ingested file of size $file_size bytes: $file"
-  fi
-
-  if [ $file_size -eq 5120 ]; then
-    echo "*** It compare well"
-  fi
 
   echo "*** ingesting the tarball in the root of the repository"
-  cat $tarfile | cvmfs_server ingest --base_dir / --tar_file - $CVMFS_TEST_REPO || return $?
+  cvmfs_server ingest --base_dir / --tar_file $tarfile $CVMFS_TEST_REPO || return $?
 
   echo "*** check catalog and data integrity"
   check_repository $CVMFS_TEST_REPO -i || return $?
@@ -176,6 +84,50 @@ cvmfs_run_test() {
   if [ $file_size -eq 5120 ]; then
     echo "*** It compare well"
   fi
+  
+  echo "*** ingesting the tarball in the root of the repository asking to create a catalog"
+  cat $tarfile | cvmfs_server ingest --catalog --base_dir / --tar_file $tarfile $CVMFS_TEST_REPO || return $?
+
+  echo "*** check catalog and data integrity"
+  check_repository $CVMFS_TEST_REPO -i || return $?
+
+  if [ ! -d $repo_dir/tarball_foo ]; then
+    return 1
+  fi
+
+  for d in a a/b a/b/c; do
+    if [ ! -d $repo_dir/tarball_foo/$d ]; then
+      echo "*** Error not found directory: $repo_dir/tarball_foo/$d"
+      return 1
+    else
+      echo "*** Ingested directory: $repo_dir/tarball_foo/$d"
+
+      for f in 1 2 3; do
+        file=$repo_dir/tarball_foo/$d/$f.txt
+        if [ ! -f $file ] || [ $(wc -c <$file) -ne 2048 ]; then
+          echo "*** Error not found file: $file"
+          return 1
+        else
+          echo "*** Ingested file of size 2048 bytes: $file"
+        fi
+      done
+
+    fi
+  done
+
+  file=$repo_dir/tarball_foo/d/e/f/foo.txt
+  file_size=$(wc -c <$file)
+  if [ ! -f $file ] || [ $file_size -ne 5120 ]; then
+    echo "*** Error not found file of size 5120: $file"
+    return 1
+  else
+    echo "*** Ingested file of size $file_size bytes: $file"
+  fi
+
+  if [ $file_size -eq 5120 ]; then
+    echo "*** It compare well"
+  fi
+
 
   return 0
 }
