FIX: fail gracefully if wget not found

diff --git a/test/src/030-missingrootcatalog/main b/test/src/030-missingrootcatalog/main
--- a/test/src/030-missingrootcatalog/main
+++ b/test/src/030-missingrootcatalog/main
@@ -16,6 +16,9 @@ cvmfs_run_test() {
   local retval=0
   local stratum1="http://cvmfs-stratum-one.cern.ch/opt"
 
+  echo -n "checking for wget... "
+  which wget > /dev/null 2>&1 && echo "done" || { echo "not found"; return 1; }
+
   echo "restarting autofs"
   autofs_switch off || return 10
   autofs_switch on  || return 11
diff --git a/test/src/554-defragcatalogrowid/main b/test/src/554-defragcatalogrowid/main
--- a/test/src/554-defragcatalogrowid/main
+++ b/test/src/554-defragcatalogrowid/main
@@ -35,8 +35,11 @@ cvmfs_run_test() {
   local repo_dir=/cvmfs/$CVMFS_TEST_REPO
   local scratch_dir=$(pwd)
 
-  echo "check for sqlite3 utility"
-  which sqlite3 || return 1
+  echo -n "checking for wget... "
+  which wget > /dev/null 2>&1 && echo "done" || { echo "not found"; return 1; }
+
+  echo -n "checking for sqlite3 utility... "
+  which sqlite3 > /dev/null 2>&1 && echo "done" || { echo "not found"; return 1; }
 
   echo "create test repository"
   create_empty_repo $CVMFS_TEST_REPO $CVMFS_TEST_USER || return $?
