fixes for integration tests

diff --git a/test/src/567-mkfswithlegacykeys/main b/test/src/567-mkfswithlegacykeys/main
--- a/test/src/567-mkfswithlegacykeys/main
+++ b/test/src/567-mkfswithlegacykeys/main
@@ -98,69 +98,69 @@ cvmfs_run_test() {
               ${CVMFS_TEST_REPO}.masterkey"
   local keys_stash="${scratch_dir}/saved_keys"
 
-  echo "create a fresh repository named $CVMFS_TEST_REPO with user $CVMFS_TEST_USER"
+  echo "*** create a fresh repository named $CVMFS_TEST_REPO with user $CVMFS_TEST_USER"
   create_repo $CVMFS_TEST_REPO $CVMFS_TEST_USER || return $?
 
-  echo "save the keys of this repository"
+  echo "*** save the keys of this repository"
   mkdir $keys_stash                                         || return 1
   sudo cp ${keys_location}/${CVMFS_TEST_REPO}.* $keys_stash || return 2
 
-  echo "manipulate the access rights of the public keys"
+  echo "*** manipulate the access rights of the public keys"
   sudo chmod 755 ${keys_stash}/* || return 3
 
-  echo "remove repository again"
+  echo "*** remove repository again"
   destroy_repo $CVMFS_TEST_REPO || return $?
 
-  echo "check that the keychain is gone from $keys_location"
+  echo "*** check that the keychain is gone from $keys_location"
   check_keys_existence "$keys_location" "$keys" && return 4
 
-  echo "plant a dummy keychain into $keys_location"
+  echo "*** plant a dummy keychain into $keys_location"
   for _key in $keys; do
     sudo touch "${keys_location}/${_key}" || return 5
   done
 
-  echo "recreate the repository with keys being in place and provide an import location (should fail)"
-  create_repo $CVMFS_TEST_REPO $CVMFS_TEST_USER NO "-k $keys_stash" && return 6
+  echo "*** recreate the repository with keys being in place and provide an import location (should fail)"
+  create_repo $CVMFS_TEST_REPO $CVMFS_TEST_USER NO -k $keys_stash && return 6
 
-  echo "check that the keys haven't been overwritten"
+  echo "*** check that the keys haven't been overwritten"
   check_keys_existence "$keys_location" "$keys"              || return 7
   check_keys_validity "$keys_location" "$keys_stash" "$keys" && return 8
 
-  echo "remove the dummy keys"
+  echo "*** remove the dummy keys"
   for _key in $keys; do
     sudo rm -f "${keys_location}/${_key}" || return 9
   done
 
-  echo "recreate the repository using the old keys"
-  create_repo $CVMFS_TEST_REPO $CVMFS_TEST_USER NO "-k $keys_stash" || return $?
+  echo "*** recreate the repository using the old keys"
+  create_repo $CVMFS_TEST_REPO $CVMFS_TEST_USER NO -k $keys_stash || return $?
 
-  echo "check that the old keys have been used"
+  echo "*** check that the old keys have been used"
   check_keys_validity "$keys_location" "$keys_stash" "$keys" || return 10
   check_keys_access_rights "$keys_location" "$keys"          || return 11
 
-  echo "remove the repository again"
+  echo "*** remove the repository again"
   destroy_repo $CVMFS_TEST_REPO || return $?
 
-  echo "check that the keychain is gone from $keys_location"
+  echo "*** check that the keychain is gone from $keys_location"
   check_keys_existence "$keys_location" "$keys" && return 12
 
-  echo "plant the keychain into $keys_location again"
+  echo "*** plant the keychain into $keys_location again"
   sudo cp ${keys_stash}/${CVMFS_TEST_REPO}.* $keys_location || return 13
 
-  echo "recreate the repository with keys already being in place"
+  echo "*** recreate the repository with keys already being in place"
   create_repo $CVMFS_TEST_REPO $CVMFS_TEST_USER NO || return $?
 
-  echo "check that the planted keys have been used"
+  echo "*** check that the planted keys have been used"
   check_keys_validity "$keys_location" "$keys_stash" "$keys" || return 14
   check_keys_access_rights "$keys_location" "$keys"          || return 15
 
-  echo "remove the repository again"
+  echo "*** remove the repository again"
   destroy_repo $CVMFS_TEST_REPO || return $?
 
-  echo "try to import keys that do not exist"
-  create_repo $CVMFS_TEST_REPO $CVMFS_TEST_USER NO "-k /tmp" && return 16
+  echo "*** try to import keys that do not exist"
+  create_repo $CVMFS_TEST_REPO $CVMFS_TEST_USER NO -k /tmp && return 16
 
-  echo "remove defunct repository"
+  echo "*** remove defunct repository"
   destroy_repo $CVMFS_TEST_REPO || return $?
 
   return 0
