[publish] Avoid deletion of non-owned leases

diff --git a/test/src/809-lease_failure/main b/test/src/809-lease_failure/main
--- a/test/src/809-lease_failure/main
+++ b/test/src/809-lease_failure/main
@@ -1,8 +1,8 @@
 #
 # Test for the cvmfs_server transaction command returns codes
-# 
+#
 # This sets up a repository with gateway and simulates the case
-# when another release manager has already taken the lock for 
+# when another release manager has already taken the lock for
 # the path we want.
 
 cvmfs_test_name="Lease contention with repository gateway"
@@ -21,7 +21,7 @@ run_transactions() {
     set_up_repository_gateway
 
     ## Transaction 1 (Creating a new deep directory sub-tree in place of a former file)
-    echo "  Starting transaction 1"
+    echo "  *** Starting transaction 1"
     cvmfs_server transaction test.repo.org
     if [ $? -ne 0 ]; then
         echo "Did not manage to  start transaction"
@@ -31,7 +31,7 @@ run_transactions() {
     mkdir -p /cvmfs/test.repo.org/new/c/d
     echo "New file" > /cvmfs/test.repo.org/new/c/d/new_file.txt
 
-    echo "  Checking that we cannot open a transaction again"
+    echo "  *** Checking that we cannot open a transaction again"
     cvmfs_server transaction test.repo.org
     retcode=$?
     if [ $retcode -ne 17 ]; then
@@ -39,7 +39,7 @@ run_transactions() {
         return 21
     fi
 
-    echo "  Publishing the transaction 1"
+    echo "  *** Publishing the transaction 1"
     cvmfs_server publish test.repo.org
     if [ $? -ne 0 ]; then
         echo "Did not manage to publish the transaction 1"
@@ -47,15 +47,17 @@ run_transactions() {
     fi
 
     # Simulating another release manager taking the lease
-    echo "  Simulating another node taking a lock on the path we want"
+    echo "  *** Simulating another node taking a lock on the path we want"
     # session token saved in  /var/spool/cvmfs/test.repo.org/session_token
     cvmfs_swissknife  lease  -u http://localhost:4929/api/v1 -a acquire -k /etc/cvmfs/keys/test.repo.org.gw -p test.repo.org/new/c
     if [ $? -ne 0 ]; then
         echo "Could not acquire lease on directory"
         return 23
     fi
+    # We need to remove the token, otherwise it's just taken by the transaction
+    rm /var/spool/cvmfs/test.repo.org/session_token || return 30
 
-    echo "  Checking that the lease is taken and that cvmfs_transaction fails"
+    echo "  *** Checking that the lease is taken and that cvmfs_transaction fails"
     cvmfs_server transaction test.repo.org/new/c
     retcode=$?
     if [ $retcode -ne 16 ]; then
