add "check_status" to .cvmfs_status.json

diff --git a/test/src/688-checkall/main b/test/src/688-checkall/main
--- a/test/src/688-checkall/main
+++ b/test/src/688-checkall/main
@@ -30,14 +30,14 @@ cvmfs_run_test() {
 
   local replica_name="$(get_stratum1_name $CVMFS_TEST_REPO)"
 
-  CVMFS_TEST_688_REPO_NAMES="${replica_name}-1 ${replica_name}-2 ${replica_name}-3"
+  CVMFS_TEST_688_REPO_NAMES="${replica_name}-1 ${replica_name}-2 ${replica_name}-3 ${replica_name}-4"
   echo "*** install a cleanup function"
   trap cleanup EXIT HUP INT TERM || return $?
 
-  echo "*** create 3 Stratum1 replicas on the same machine"
+  echo "*** create 4 Stratum1 replicas on the same machine"
   load_repo_config $CVMFS_TEST_REPO
 
-  for num in 1 2 3; do
+  for num in 1 2 3 4; do
     create_stratum1 ${replica_name}-$num                   \
                     $CVMFS_TEST_USER                       \
                     $CVMFS_STRATUM0                        \
@@ -55,6 +55,9 @@ cvmfs_run_test() {
   echo "*** removing old checks.log"
   rm -f /var/log/cvmfs/checks.log
 
+  echo "*** corrupting replica 4"
+  rm -f /srv/cvmfs/${replica_name}-4/.cvmfswhitelist
+
   echo "*** running cvmfs_server check -a"
   sudo cvmfs_server check -a || return 10
 
@@ -62,12 +65,15 @@ cvmfs_run_test() {
   cat /var/log/cvmfs/checks.log
 
   echo "*** checking if check worked on test repo and replicas 1 and 3"
-  curl -f -s "$(get_repo_url $CVMFS_TEST_REPO)/.cvmfs_status.json"|grep last_check  || return 50
-  curl -f -s "$(get_repo_url ${replica_name}-1)/.cvmfs_status.json"|grep last_check || return 51
-  curl -f -s "$(get_repo_url ${replica_name}-3)/.cvmfs_status.json"|grep last_check || return 52
+  curl -f -s "$(get_repo_url $CVMFS_TEST_REPO)/.cvmfs_status.json"  | grep check_status.*succeeded || return 50
+  curl -f -s "$(get_repo_url ${replica_name}-1)/.cvmfs_status.json" | grep check_status.*succeeded || return 51
+  curl -f -s "$(get_repo_url ${replica_name}-3)/.cvmfs_status.json" | grep check_status.*succeeded || return 52
 
   echo "*** verifying check did not run on replica 2"
-  curl -f -s "$(get_repo_url ${replica_name}-2)/.cvmfs_status.json"|grep last_check && return 53
+  curl -f -s "$(get_repo_url ${replica_name}-2)/.cvmfs_status.json" | grep last_check && return 53
+
+  echo "*** verifying check failed on replica 4"
+  curl -f -s "$(get_repo_url ${replica_name}-4)/.cvmfs_status.json" | grep check_status.*failed || return 54
 
   return 0
 }
