address review

diff --git a/test/src/400-ducc-ingest_images/main b/test/src/400-ducc-ingest_images/main
--- a/test/src/400-ducc-ingest_images/main
+++ b/test/src/400-ducc-ingest_images/main
@@ -2,63 +2,64 @@ cvmfs_test_name="DUCC container ingestion"
 cvmfs_test_autofs_on_startup=true
 cvmfs_test_suites="ducc"
 
-registry=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1)
-recipe="$(pwd)/$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1).yaml"
-repository="$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1).cern.ch"
-ducc_log="$(pwd)/$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1).log"
-ducc_err="$(pwd)/$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1).err"
+CVMFS_TEST400_REGISTRY=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1)
+CVMFS_TEST400_RECIPE="$(pwd)/$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1).yaml"
+CVMFS_TEST400_REPOSITORY="$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1).cern.ch"
+CVMFS_TEST400_DUCC_LOG="$(pwd)/$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1).log"
+CVMFS_TEST400_DUCC_ERR="$(pwd)/$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 8 | head -n 1).err"
+CVMFS_TEST400_REMOVE_PLUGIN=0
+
 
 ducc_test_400_clean_up() {
-    printf "Cleaning up..."
-
-    mv /etc/cvmfs/default.local.bk /etc/cvmfs/default.local
-    rm -f /etc/cvmfs/config.d/$repository.conf
-    #delete the docker images
-
-    # delete the CVMFS repo
-    printf "Deleting CVMFS repo..."
-    cvmfs_server rmfs -f $repository >> /dev/null
-    printf "done\n"
+    echo -n "Cleaning up..."
 
     export DUCC_DOCKER_REGISTRY_PASS=""
 
     # delete the recipe file
-    rm $recipe
+    rm $CVMFS_TEST400_RECIPE
     # delete the logs and error from ducc
-    rm $ducc_log
-    rm $ducc_err
+    rm $CVMFS_TEST400_DUCC_LOG
+    rm $CVMFS_TEST400_DUCC_ERR
 
     # stop and delete the registry container
-    printf "Stopping and deleting docker registry..."
-    docker stop $registry >> /dev/null
-    docker rm $registry >> /dev/null
-    printf "done\n"
+    echo -n "Stopping and deleting docker registry..."
+    docker stop $CVMFS_TEST400_REGISTRY >> /dev/null
+    docker rm $CVMFS_TEST400_REGISTRY >> /dev/null
+    echo "done"
 
-    printf "Reseting initial docker configuration..."
-    rm -f /etc/docker/daemon.json
-    mv /etc/docker/daemon.json.bk /etc/docker/daemon.json
+    if [ CVMFS_TEST400_REMOVE_PLUGIN -eq 1 ]
+    then
+        echo -n "Reseting initial docker configuration..."
+        rm -f /etc/docker/daemon.json
+        mv /etc/docker/daemon.json.bk /etc/docker/daemon.json
+        systemctl restart docker
+    fi
 
-    systemctl restart docker
-
-    printf "done\n"
+    echo "done"
 }
 
 cvmfs_run_test() {
-    trap ducc_test_400_clean_up EXIT
+    trap ducc_test_400_clean_up EXIT HUP INT TERM
 
-    # change the docker configuration to run thin images
-    printf "*** Changing the docker configuration to run thin images..."
+    docker plugin ls --format {{.Name}} | grep cvmfs/graphdriver
+    if [ $? -ne 0 ]
+    then
 
-    # saving old docker configuration
-    mkdir -p /etc/docker
-    touch /etc/docker/daemon.json
-    mv /etc/docker/daemon.json /etc/docker/daemon.json.bk
+        # change the docker configuration to run thin images
+        echo -n "*** Changing the docker configuration to run thin images..."
 
-    # installing thin image plugin
-    docker plugin install --grant-all-permissions cvmfs/graphdriver
+        # saving old docker configuration
+        mkdir -p /etc/docker
+        touch /etc/docker/daemon.json
+        mv /etc/docker/daemon.json /etc/docker/daemon.json.bk
 
-    # change configuration file
-    cat > /etc/docker/daemon.json << EOL
+        CVMFS_TEST400_REMOVE_PLUGIN=1
+
+        # installing thin image plugin
+        docker plugin install --grant-all-permissions cvmfs/graphdriver || return 150
+
+        # change configuration file
+        cat > /etc/docker/daemon.json << EOL
 {
   "experimental": true,
   "storage-driver": "cvmfs/graphdriver",
@@ -68,83 +69,75 @@ cvmfs_run_test() {
 }
 EOL
 
-    # finally restarting docker
-    systemctl restart docker.service
-    docker plugin enable cvmfs/graphdriver
-    printf "done\n"
+        # finally restarting docker
+        systemctl restart docker.service || return 151
+        docker plugin enable cvmfs/graphdriver || return 152
+        echo "done"
+    fi
 
     # start by running the docker registry on localhost
-    printf "*** Starting docker registry for tests..."
-    docker run -d -p 5000:5000 --name $registry registry:2 >> /dev/null || return 3
-    printf "done\n"
+    echo -n "*** Starting docker registry for tests..."
+    docker run -d -p 5000:5000 --name $CVMFS_TEST400_REGISTRY registry:2 >> /dev/null || return 3
+    echo "done"
 
     # create a simple recipe file for the repository manager in the local dir
-    printf "*** Creating recipe file..."
-    cat > $recipe  << EOL
+    echo -n "*** Creating recipe file..."
+    cat > $CVMFS_TEST400_RECIPE  << EOL
 version: 1
 user: mock_user
-cvmfs_repo: '$repository'
+cvmfs_repo: '$CVMFS_TEST400_REPOSITORY'
 output_format: '\$(scheme)://localhost:5000/mock/\$(image)'
 input:
     - 'https://registry.hub.docker.com/library/ubuntu:latest'
     - 'https://registry.hub.docker.com/library/centos:centos6'
 EOL
-    printf "done\n"
+    echo "done"
 
     # set the password to access the docker hub
     export DUCC_DOCKER_REGISTRY_PASS=mock_pass
 
     # crete the repository where to store the content
-    printf "*** Creating CVMFS repo..."
-    create_empty_repo $repository $USER || return $?
-    printf "done\n"
+    echo -n "*** Creating CVMFS repo..."
+    create_empty_repo $CVMFS_TEST400_REPOSITORY $USER || return $?
+    echo "done"
 
-    printf "*** Changing configuration to read the new repo..."
+    echo -n "*** Changing configuration to read the new repo..."
     # setting the configuration for the repo
     mv /etc/cvmfs/default.local /etc/cvmfs/default.local.bk
+    
+    echo "*** Starting test."
 
-    cat > /etc/cvmfs/default.local << EOL
-CVMFS_REPOSITORIES=$repository
-CVMFS_HTTP_PROXY="DIRECT"
-EOL
-
-    cat > /etc/cvmfs/config.d/$repository.local << EOL
-CVMFS_SERVER_URL=http://localhost/cvmfs/$repository/
-CVMFS_PUBLIC_KEY=/etc/cvmfs/keys/$repository.pub
-EOL
-    printf "done\n"
-
-    printf "*** Starting test.\n"
-
-    printf "*** Converting recipe..."
-    cvmfs_ducc convert $recipe 1> $ducc_log 2> $ducc_err || return 101
-    grep -q "level=error" $ducc_err
+    echo -n "*** Converting recipe..."
+    cvmfs_ducc convert $CVMFS_TEST400_RECIPE 1> $CVMFS_TEST400_DUCC_LOG 2> $CVMFS_TEST400_DUCC_ERR || return 101
+    grep -q "level=error" $CVMFS_TEST400_DUCC_ERR
     while [ $? -ne 1 ]
     do
-        printf "*** Some error during conversion, let's do it again.\nConverting recipe..."
-        rm $ducc_log $ducc_err
-        cvmfs_ducc convert $recipe 1> $ducc_log 2> $ducc_err || return 101
-        grep -q "level=error" $ducc_err
+        echo -n "*** Some error during conversion, let's do it again. Converting recipe..."
+        rm $CVMFS_TEST400_DUCC_LOG $CVMFS_TEST400_DUCC_ERR
+        cvmfs_ducc convert $CVMFS_TEST400_RECIPE 1> $CVMFS_TEST400_DUCC_LOG 2> $CVMFS_TEST400_DUCC_ERR || return 101
+        grep -q "level=error" $CVMFS_TEST400_DUCC_ERR
     done
-    printf "\n*** Convert recipe successfully\n"
+    echo "*** Convert recipe successfully"
 
-    printf "*** Check integrity of the repository...\n"
-    check_repository $repository -i || return 102
-    printf "*** Repository checked successfully\n"
+    echo "*** Check integrity of the repository..."
+    check_repository $CVMFS_TEST400_REPOSITORY -i || return 102
+    
+    echo "*** Repository checked successfully"
 
-    singularity exec /cvmfs/$repository/registry.hub.docker.com/library/ubuntu\:latest/ echo token-abc | grep "token-abc" || return 103
-    singularity exec /cvmfs/$repository/registry.hub.docker.com/library/centos\:centos6/ echo token-xyz | grep "token-xyz" || return 104
+    singularity exec /cvmfs/$CVMFS_TEST400_REPOSITORY/registry.hub.docker.com/library/ubuntu\:latest/ echo token-abc | grep "token-abc" || return 103
+    singularity exec /cvmfs/$CVMFS_TEST400_REPOSITORY/registry.hub.docker.com/library/centos\:centos6/ echo token-xyz | grep "token-xyz" || return 104
+    
+    echo "*** Singularity conversion worked fine"
 
-    systemctl restart docker.service
+    systemctl restart docker.service || return 153
 
     docker run "localhost:5000/mock/library/ubuntu:latest" echo "token-123" | grep "token-123" || return 105
     docker run "localhost:5000/mock/library/centos:centos6" echo "token-321" | grep "token-321" || return 106
 
     # add other possible tests
 
-    printf "*** Test successful\n"
+    echo "*** Test successful"
 
-    return
-
+    return 0
 }
 
