FIX: 615 - external files in extra HTTP server

diff --git a/test/src/615-externaldata/main b/test/src/615-externaldata/main
--- a/test/src/615-externaldata/main
+++ b/test/src/615-externaldata/main
@@ -17,18 +17,35 @@ get_chunk_count() {
   attr -qg chunks "$full_file_path"
 }
 
+CVMFS_TEST_615_HTTP_PID=
+cleanup() {
+  echo "running cleanup()"
+  [ -z $CVMFS_TEST_615_HTTP_PID ] || sudo kill $CVMFS_TEST_615_HTTP_PID
+}
+
 cvmfs_run_test() {
   logfile=$1
+  src_location=$2
   local repo_dir="/cvmfs/${CVMFS_TEST_REPO}"
+  local scratch_dir="$(pwd)"
 
   echo "create a fresh repository named $CVMFS_TEST_REPO with user $CVMFS_TEST_USER"
   echo "Note: cvmfs_server mkfs -X --> enabled external files"
   create_empty_repo $CVMFS_TEST_REPO $CVMFS_TEST_USER NO -X -Z none || return $?
 
-  echo "get some global base paths"
+  echo "get some global base paths and configs"
   load_repo_config $CVMFS_TEST_REPO
   local cvmfs_mnt="${CVMFS_SPOOL_DIR}/rdonly"
   local cvmfs_cache="${CVMFS_SPOOL_DIR}/cache/$CVMFS_TEST_REPO"
+  local http_port=8615
+  local external_http_base="http://localhost:$http_port"
+  local client_config="/etc/cvmfs/repositories.d/${CVMFS_TEST_REPO}/client.conf"
+
+  echo "install a desaster cleanup"
+  trap cleanup EXIT HUP INT TERM || return $?
+
+  echo "configure external data location"
+  echo "CVMFS_EXTERNAL_URL=$external_http_base" | sudo tee --append $client_config
 
   echo "fill repository with some files"
   start_transaction $CVMFS_TEST_REPO                     || return $?
@@ -50,12 +67,36 @@ cvmfs_run_test() {
   [ -f "$object_file" ] || return 7
   echo "File in backend is $object_file"
 
-  local external_storage="$(get_local_repo_storage $CVMFS_TEST_REPO)/external"
+  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
+
+  local external_storage="${scratch_dir}/external_files"
   echo "Creating external storage directory '$external_storage'"
   mkdir -p $external_storage || return 51
 
+  echo "Make sure the file is NOT in the repository storage but instead in the external area"
+  mkdir -p ${external_storage}/external
+  mv "$object_file" ${external_storage}/external/file || return 52
+
+  echo "Check the external file data (should fail to read - external storage not served yet)"
+  is_external_file ${cvmfs_mnt}/external/file || return 20
+  ! cat ${repo_dir}/external/file             || return 22
+
+  echo "start an HTTP server to serve external files"
+  local http_log="${scratch_dir}/http.log"
+  CVMFS_TEST_615_HTTP_PID="$(open_http_server $external_storage $http_port $http_log)"
+  kill -0 $CVMFS_TEST_615_HTTP_PID || { echo "fail"; return 4; }
+  echo "HTTP server running with PID $CVMFS_TEST_615_HTTP_PID"
+
+  echo "Check the external file data"
+  is_external_file ${cvmfs_mnt}/external/file               || return 20
+  [ x"$(cat ${repo_dir}/external/file)" == x"Hello World" ] || return 22
+
+  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
+
+  echo "copy chunked file into external storage"
+  cp chunked_file "${external_storage}/chunked_file" || return 52
+
   echo "verify chunked files are really properly chunked and readable"
-  cp chunked_file "$(get_local_repo_storage $CVMFS_TEST_REPO)/chunked_file" || return 52
   local chunked_true_hash=$(cat chunked_file | sha1sum | awk '{print $1;}')
   local chunked_cvmfs_hash=$(get_content_hash ${cvmfs_mnt}/chunked_file)
   local chunked_cvmfs_read=$(cat ${repo_dir}/chunked_file | sha1sum | awk '{print $1;}')
@@ -78,12 +119,7 @@ cvmfs_run_test() {
     return 27
   fi
 
-  echo "Make sure the file is NOT in the repository storage but instead in the external area"
-  mv "$object_file" ${external_storage}/file || return 52
-
-  echo "Check the external file data"
-  is_external_file ${cvmfs_mnt}/external/file               || return 20
-  [ x"$(cat ${repo_dir}/external/file)" == x"Hello World" ] ||return 22
+  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
 
   local cache_object="${cvmfs_cache}/$(get_hash_path $object_hash)"
   echo "Verify the expected file ($cache_object) is in the cache."
@@ -102,8 +138,8 @@ cvmfs_run_test() {
 
   echo "Remove cached and external copy of the file; only copy"
   echo "is in the backend storage, which should not be used."
-  mv ${external_storage}/file "$object_file" || return 55
-  sudo rm -f $cache_object                   || return 56
+  mv ${external_storage}/external/file "$object_file" || return 55
+  sudo rm -f $cache_object                            || return 56
 
   echo "Make sure access fails without the external copy."
   if cat ${repo_dir}/external/file; then
