test/src/066-killall: make work with `set -e`
Dropped the subsequent `wait` as it's impossible for it be effectual,
also its outcomes are not tested.

 + sudo cvmfs_config killall
 Terminating cvmfs_config processes... OK
 Terminating cvmfs2 processes... Reload CRASHED! CernVM-FS mountpoints unusable.
 atlas.cern.ch: Connecting to CernVM-FS loader... done
 atlas.cern.ch: Entering maintenance mode
 atlas.cern.ch: Draining out kernel caches (up to 60s)
 atlas.cern.ch: Blocking new file system calls
 atlas.cern.ch: Waiting for active file system calls
 atlas.cern.ch: Saving inode tracker
 atlas.cern.ch: Saving negative entry cache
 atlas.cern.ch: Saving page cache entry tracker
 atlas.cern.ch: Saving chunk tables
 atlas.cern.ch: Saving inode generation
 atlas.cern.ch: Saving fuse state
 atlas.cern.ch: Saving watchdog listener state
 atlas.cern.ch: Saving open files table
 atlas.cern.ch: Unloading Fuse module
 atlas.cern.ch: Waiting for the delivery of SIGUSR1...
 atlas.cern.ch: Re-Loading Fuse module
 OK
 Unmounting stale mount points... OK
 Cleaning up run-time variable data... OK
 Reloading autofs... OK
 src/066-killall/main: line 165: 56837 Killed                  sudo cvmfs_config reload
 + echo 'Wait for reload to finish'
 Wait for reload to finish
 + wait 56837
 [1]+  Exit 137                bash -c '

diff --git a/test/src/066-killall/main b/test/src/066-killall/main
--- a/test/src/066-killall/main
+++ b/test/src/066-killall/main
@@ -180,11 +180,11 @@ cvmfs_run_test() {
 
   sudo cvmfs_config killall || return 20
   echo "Wait for reload to finish"
-  wait $reload_pid
+  # non-zero exit code is legit but not tested for, got 137 as of 2026-05-30
+  wait $reload_pid || true
 
   echo "Killall once again because we don't know where the reloaded was interrupted"
   sudo cvmfs_config killall || return 30
-  wait $!
 
   if [ "$(uname)" != "Linux" ]; then
     # specific killall options are not meant
