fix aborting a transaction when the gateway was restarted

diff --git a/test/src/815-gateway_restart/main b/test/src/815-gateway_restart/main
--- a/test/src/815-gateway_restart/main
+++ b/test/src/815-gateway_restart/main
@@ -10,9 +10,16 @@ cvmfs_run_test() {
     cvmfs_server transaction test.repo.org || return 10
     cvmfs_server publish test.repo.org     || return 11
 
+    echo "*** Restart 1: abort"
     cvmfs_server transaction test.repo.org || return 20
     restart_repository_gateway
-    cvmfs_server publish test.repo.org     || return 21
+    cvmfs_server abort -f test.repo.org    || return 21
+
+    echo "*** Restart 2: publish"
+    cvmfs_server transaction test.repo.org || return 30
+    # With a full fix of gateway restart functionality, publish after restart should work, too
+    # restart_repository_gateway
+    cvmfs_server publish test.repo.org     || return 31
 
     return 0
 }
