[test] add k8s daemonset test

diff --git a/test/container/006-k8s/main b/test/container/006-k8s/main
--- a/test/container/006-k8s/main
+++ b/test/container/006-k8s/main
@@ -1,6 +1,8 @@
 cvmfs_test_name="provide cvmfs to k8s pods"
 cvmfs_test_suites="quick"
 
+# Taking https://github.com/sfiligoi/prp-osg-cvmfs as a blueprint
+
 cleanup() {
   echo "running cleanup()"
 
@@ -28,29 +30,71 @@ cvmfs_run_test() {
   local image_name=$(docker inspect $image_id | jq -r .[0].RepoTags[0])
   echo "*** Image name: $image_name"
 
-  echo "*** deploy cvmfs workspace"
+  echo "*** deploy cvmfs k8s area"
   k8s_kubectl apply -f ${script_location}/deploy/namespace-cvmfs.yaml || return 20
-  k8s_kubectl apply -f ${script_location}/deploy/user-cvmfs.yaml      || return 21
+  k8s_kubectl apply -f ${script_location}/deploy/account-cvmfs.yaml   || return 21
 
-  echo "*** deploy cvmfs storage bindings"
-  k8s_kubectl apply -f ${script_location}/deploy/pv-cvmfs-root.yaml   || return 22
+  echo "*** deploy cvmfs 'workspace' persistent volume"
+  k8s_kubectl apply -f ${script_location}/deploy/pv-cvmfs-noderoot.yaml || return 22
 
   k8s_kubectl get storageclass
   k8s_kubectl get persistentvolume
   k8s_kubectl get -A persistentvolumeclaim
 
-  #k8s_kubectl create -f deployments/kubernetes/csi-attacher-rbac.yaml           || return 31
-  ## TODO(jblomer): use upstream yaml once fixed
-  #k8s_kubectl create -f $script_location/csi-provisioner-rbac.yaml              || return 32
-  #k8s_kubectl create -f deployments/kubernetes/csi-nodeplugin-rbac.yaml         || return 33
-  #k8s_kubectl create -f $script_location/csi-cvmfsplugin-attacher.yaml          || return 34
-  #k8s_kubectl create -f deployments/kubernetes/csi-cvmfsplugin-provisioner.yaml || return 35
+  echo "*** deploy nodeplugin daemonset (cvmfs service container)"
+  k8s_kubectl apply -f \
+    ${script_location}/deploy/daemonset-cvmfs-nodeplugin.yaml || return 30
 
+  echo "*** waiting for daemonset to become available..."
+  local retries=30
+  local nready=0
+  while [ $retries -ge 0 ]; do
+    sleep 3
+    nready=$(k8s_kubectl get --namespace cvmfs daemonset cvmfs-nodeplugin -o jsonpath="{.status.numberReady}")
+    if [ $nready -eq 1 ]; then
+      break
+    fi
+    retries=$((retries-1))
+    echo "   ... still waiting"
+  done
+  echo "*** retries: $retries"
 
-  echo "*** run demo POD"
-  #k8s_kubectl create -f example/storageclass.yaml || return 40
-  #k8s_kubectl create -f example/pvc.yaml          || return 41
-  #k8s_kubectl create -f example/pod.yaml          || return 42
+  k8s_kubectl describe --namespace cvmfs daemonset cvmfs-nodeplugin  || return 31
+  k8s_kubectl get pods --namespace cvmfs || return 32
+  local cvmfs_pods=$(k8s_kubectl get pods --namespace cvmfs --output=jsonpath='{.items[*].metadata.name}')
+  k8s_kubectl logs --namespace cvmfs $cvmfs_pods
+
+  echo "*** provide individual cvmfs repositories as volumes"
+  k8s_kubectl apply -f ${script_location}/deploy/pv-cvmfs-alice.yaml || return 40
+  k8s_kubectl get persistentvolumeclaim
+
+  echo "*** run demo job that accesses /cvmfs"
+  k8s_kubectl apply -f ${script_location}/deploy/job-test.yaml   || return 80
+
+  # wait for completion as background process - capture PID
+  k8s_kubectl wait --for=condition=complete job/list-cvmfs &
+  local completion_pid=$!
+  # wait for failure as background process - capture PID
+  k8s_kubectl wait --for=condition=failed job/list-cvmfs && exit 1 &
+  local failure_pid=$!
+  # capture exit code of the first subprocess to exit
+  wait -n $completion_pid $failure_pid
+  local job_status=$?
+  kill $completion_pid
+  kill $failure_pid
+
+  local job_pods=$(k8s_kubectl get pods --selector=job-name=list-cvmfs --output=jsonpath='{.items[*].metadata.name}')
+  echo "*** pods: $job_pods"
+  k8s_kubectl logs $job_pods
+
+  if [ $job_status -ne 0 ]; then
+    echo "Listing cvmfs failed"
+    return 80
+  fi
+
+  echo "*** Adding a new node"
+  # TODO
+  # minikube node add
 
   return 0
 }
