test/src/666-ingestownership: fix post-hoc userdel on CentOS 9 with `set -e`
 + sudo userdel cvmfstestuser
 userdel: user cvmfstestuser is currently used by process 7629
 [1]+  Exit 8                  bash -c '

diff --git a/test/src/666-ingestownership/main b/test/src/666-ingestownership/main
--- a/test/src/666-ingestownership/main
+++ b/test/src/666-ingestownership/main
@@ -13,6 +13,12 @@ cleanup() {
   fi
 
   if [ "x$CVMFS_TEST666_TEST_UID" != "x" ]; then
+    # systemd user session automatically started by `sudo` fails userdel. Seen on CentOS 9.
+    # Waiting for it to terminate on its own takes 10 seconds.
+    sudo kill $(ps -u cvmfstestuser -o pid=) || true
+    while ps -u cvmfstestuser -o pid= >/dev/null; do
+      sleep 1
+    done
     sudo userdel cvmfstestuser
   fi
 
