Modify /etc/sudoers for Mac

diff --git a/cvmfs/cvmfs_config b/cvmfs/cvmfs_config
--- a/cvmfs/cvmfs_config
+++ b/cvmfs/cvmfs_config
@@ -119,6 +119,12 @@ cvmfs_setup()
       echo "Cannot configure fuse!"
       exit 1
     fi
+    
+    # configure sudoers on Mac OS
+    if ! configure_sudoers; then
+      echo "Cannot configure sudoers"
+      exit 1
+    fi
   fi
 
   if [ $noservice -eq 0 ]; then
@@ -649,12 +655,12 @@ add_cvmfs_group()
 {
   case $sys_arch in
     Linux )
-     if ! check_group cvmfs; then
+     if ! check_group "cvmfs"; then
        /usr/sbin/groupadd -r cvmfs
      fi ;;
 
     Darwin )
-      if ! check_group cvmfs; then
+      if ! check_group "cvmfs"; then
         #find un-used group id starting from 10000
         local gid=10000
         while true; do
@@ -697,7 +703,7 @@ add_cvmfs_user()
           uid=$[$uid +1]
         done
 
-	if check_group cvmfs; then
+	if check_group "cvmfs"; then
     gid=$(dscl . read /groups/cvmfs PrimaryGroupID | awk {'print $NF'})
   else
     echo "CVMFS group does not exists."
@@ -876,6 +882,16 @@ configure_autofs()
      exit 1 ;;
 
   esac
+}
+
+configure_sudoers()
+{
+  if [ $sys_arch == 'Darwin' ]; then
+    sudo perl -n -i -e \
+      'print if !/^\%everyone\s+ALL=\(cvmfs:cvmfs\)/; 
+       print "%everyone ALL=(cvmfs:cvmfs) NOPASSWD: /usr/local/bin/cvmfs2\n" if eof;'\
+    /etc/sudoers
+  fi
 }
 
 check_fuse_config()
