logging for file system traversal

diff --git a/cvmfs/cvmfs_server b/cvmfs/cvmfs_server
--- a/cvmfs/cvmfs_server
+++ b/cvmfs/cvmfs_server
@@ -52,7 +52,7 @@ create_cert() {
    chmod 444 $key $crt
    chown $user $master_key $master_pub
    echo "done"
-} 
+}
 
 
 create_whitelist() {
@@ -86,7 +86,7 @@ create_whitelist() {
 
   rm -f ${whitelist}.unsigned ${whitelist}.signature ${whitelist}.sha1
   echo "done"
-  
+
   if [ x"$upload_pipe" != x ]; then
     echo "$whitelist, /.cvmfswhitelist" > $upload_pipe
   fi
@@ -96,7 +96,7 @@ create_whitelist() {
 get_expiry() {
   local name=$1
   local stratum0=$2
-  
+
   local expires=$(curl $stratum0/.cvmfswhitelist 2>/dev/null | head -2 | tail -1 | tail -c15)
   local year=$(echo $expires | head -c4)
   local month=$(echo $expires | head -c6 | tail -c2)
@@ -112,7 +112,7 @@ get_expiry() {
 
 get_local_upstream() {
   local upstream=$1
-  
+
   if [ x$(echo "$upstream" | cut -d: -f1) = x"local" ]; then
     echo "$(echo $upstream | cut -d: -f2)"
   else
@@ -123,7 +123,7 @@ get_local_upstream() {
 
 get_pipe_upstream() {
   local upstream=$1
-  
+
   if [ x$(echo "$upstream" | cut -d: -f1) = x"pipe" ]; then
     echo "$(echo $upstream | cut -d: -f2)"
   else
@@ -195,7 +195,9 @@ publish() {
   publish_before_hook $name
   sudo /bin/mount -o remount,ro /cvmfs/$name
   local base_hash=$(attr -qg root_hash ${spool_dir}/rdonly)
-   
+  local log_level=
+  [ "x$CVMFS_LOG_LEVEL" != x ] && log_level="-z $CVMFS_LOG_LEVEL"
+
   $user_shell "cvmfs_sync -x -u /cvmfs/$name \
     -s ${spool_dir}/scratch \
     -c ${spool_dir}/rdonly \
@@ -205,7 +207,8 @@ publish() {
     -d ${spool_dir}/digests \
     -l $repository_dir \
     -w $stratum0 \
-    -o ${spool_dir}/tmp/manifest" || die "Synchronization failed"
+    -o ${spool_dir}/tmp/manifest \
+    $log_level" || die "Synchronization failed"
   $user_shell "cvmfs_sign -c /etc/cvmfs/keys/${name}.crt \
     -k /etc/cvmfs/keys/${name}.key \
     -n $name \
@@ -230,7 +233,7 @@ publish() {
 create_repository_skeleton() {
   local directory=$1
   local user=$2
-  
+
   echo -n "Creating repository skeleton in ${directory}..."
   mkdir -p ${directory}/data
   local i=0
@@ -248,7 +251,7 @@ mkfs() {
   local name=$1
   local stratum0=$2
   local upstream=$3
-  
+
   local spool_dir="/var/spool/cvmfs/${name}"
   local scratch_dir="${spool_dir}/scratch"
   local rdonly_dir="${spool_dir}/rdonly"
@@ -366,7 +369,7 @@ EOF
   fi
   reload_apache > /dev/null
   echo "done"
-  
+
   echo -n "Create Initial Repository... "
   create_whitelist $name $cvmfs_user $upstream $temp_dir > /dev/null
   su $cvmfs_user -c "cvmfs_sync -n \
@@ -384,7 +387,7 @@ EOF
     -d $pipe_digests \
     -l $repository_dir" > /dev/null
   echo "done"
-  
+
   echo -n "Mounting CernVM-FS Storage... "
   cat >> /etc/fstab << EOF
 $name $rdonly_dir cvmfs no_reload 0 0 # added by CernVM-FS for $name
@@ -428,7 +431,7 @@ rmfs() {
   echo -n "Removing spool area... "
   rm -rf $spool_dir /cvmfs/$name
   echo done
-  
+
   local repository_dir=$(get_local_upstream $upstream)
   if [ "x"$repository_dir != x ]; then
     echo -n "Removing repository storage... "
@@ -482,9 +485,9 @@ usage() {
    echo "\
 CernVM-FS Server Tool
 Commands:
-  mkfs <fully qualified name> [-w stratum0 url] [-u upstream storage]: 
+  mkfs <fully qualified name> [-w stratum0 url] [-u upstream storage]:
                Create a new repository with a given name
-  skeleton <directory>:    
+  skeleton <directory>:
                Create repository skeleton in directory
   rmfs:        Remove the repository
   resign:      Re-sign the 30 day whitelist
@@ -544,7 +547,7 @@ case $1 in
         ;;
       esac
     done
-    mkfs $CVMFS_REPOSITORY_NAME $STRATUM0 $UPSTREM 
+    mkfs $CVMFS_REPOSITORY_NAME $STRATUM0 $UPSTREM
     ;;
   rmfs)
     [ x"$CVMFS_REPOSITORY_NAME" = x ] && die "Which repository?"
