fix cvmfs library cannot find

diff --git a/cvmfs/cvmfs_config b/cvmfs/cvmfs_config
--- a/cvmfs/cvmfs_config
+++ b/cvmfs/cvmfs_config
@@ -210,8 +210,10 @@ cvmfs_chksetup() {
   for library in $cvmfs_libs
   do
     if ! test -f /usr/lib/$library && ! test -f /usr/lib64/$library; then
-      echo "Error: $library not found"
-      num_errors=$(($num_errors+1))
+      if ! test -f /usr/lib/i386-linux-gnu/$library && ! test -f /usr/lib/x86_64-linux-gnu/$library; then
+        echo "Error: $library not found"
+        num_errors=$(($num_errors+1))
+      fi
     fi
   done
 
