FIX: logging in cvmfs_server health check

diff --git a/cvmfs/cvmfs_server b/cvmfs/cvmfs_server
--- a/cvmfs/cvmfs_server
+++ b/cvmfs/cvmfs_server
@@ -1519,6 +1519,7 @@ __hc_transition() {
   local name="$1"
   local transition="$2"
   local msg=""
+  local retcode=0
 
   case $transition in
     rw_umount)     msg="Trying to umount /cvmfs/${name}"             ;;
@@ -1530,11 +1531,13 @@ __hc_transition() {
     *)             exit 2                                            ;;
   esac
 
-  echo -n "Note: ${msg}... "
+  echo -n "Note: ${msg}... " >&2
   if run_suid_helper $transition $name; then
-    echo "success"
+    echo "success" >&2
+    to_syslog_for_repo $name "${msg}... success"
   else
-    echo "fail"
+    echo "fail" >&2
+    to_syslog_for_repo $name "${msg}... fail"
     exit 1
   fi
 }
