opportunistically retry umount with force

diff --git a/cvmfs/cvmfs_server b/cvmfs/cvmfs_server
--- a/cvmfs/cvmfs_server
+++ b/cvmfs/cvmfs_server
@@ -1133,14 +1133,22 @@ close_transaction() {
   local tx_lock="${CVMFS_SPOOL_DIR}/in_transaction"
   local tmp_dir="${CVMFS_SPOOL_DIR}/tmp"
 
+  # if not explicitly asked, try if umounting works without force
+  if [ $use_fd_fallback -eq 0 ]; then
+    if ! cvmfs_suid_helper rw_umount     $name || \
+       ! cvmfs_suid_helper rdonly_umount $name; then
+      use_fd_fallback=1
+    fi
+  fi
+
+  # if explicitly asked for or the normal umount failed we apply more force
   if [ $use_fd_fallback -ne 0 ]; then
     cvmfs_suid_helper rw_lazy_umount     $name
     cvmfs_suid_helper kill_cvmfs         $name
     cvmfs_suid_helper rdonly_lazy_umount $name
-  else
-    cvmfs_suid_helper rw_umount $name
-    cvmfs_suid_helper rdonly_umount $name
   fi
+
+  # continue with the remounting
   cvmfs_suid_helper clear_scratch $name
   [ ! -z "$tmp_dir" ] && rm -fR "${tmp_dir}"/*
   cvmfs_suid_helper rdonly_mount $name > /dev/null
