Refactor: extract a minimal GC run function

diff --git a/cvmfs/cvmfs_server b/cvmfs/cvmfs_server
--- a/cvmfs/cvmfs_server
+++ b/cvmfs/cvmfs_server
@@ -3746,11 +3746,10 @@ gc() {
   local preserve_timestamp=0
   local timestamp_threshold=""
   local force=0
-  local open_transaction=1
 
   # optional parameter handling
   OPTIND=1
-  while getopts "ldr:t:fk" option
+  while getopts "ldr:t:f" option
   do
     case $option in
       l)
@@ -3767,9 +3766,6 @@ gc() {
       ;;
       f)
         force=1
-      ;;
-      k)
-        open_transaction=0
       ;;
       ?)
         shift $(($OPTIND-2))
@@ -3822,66 +3818,97 @@ gc() {
     # sanity checks
     check_repository_compatibility $name
     is_garbage_collectable $name || die "Garbage Collection is not enabled for $name"
-    is_in_transaction      $name && die "Cannot run garbage collection while in a transaction"
     is_owner_or_root       $name || die "Permission denied: Repository $name is owned by $user"
+    is_in_transaction      $name && die "Cannot run garbage collection while in a transaction"
+
     local head_timestamp="$(cvmfs_swissknife info -r $CVMFS_STRATUM0 -t)"
     [ $head_timestamp -gt $preserve_timestamp ] || die "Latest repository revision is older than given timestamp"
 
-    # create user shell
-    local user_shell="$(get_user_shell $name)"
-
-    # prepare swissknife commands
-    local new_manifest="${CVMFS_SPOOL_DIR}/tmp/manifest"
+    # figure out the URL of the repository
     local repository_url="$CVMFS_STRATUM0"
     if is_stratum1 $name; then
       [ ! -z $CVMFS_STRATUM1 ] || die "Missing CVMFS_STRATUM1 URL in server.conf"
       repository_url="$CVMFS_STRATUM1"
-      open_transaction=0
     fi
+
+    # generate the garbage collection configuration
     local additional_switches=""
     [ $list_deleted_objects -ne 0 ] && additional_switches="$additional_switches -l"
     [ $dry_run              -ne 0 ] && additional_switches="$additional_switches -d"
     [ $preserve_revisions   -ge 0 ] && additional_switches="$additional_switches -h $preserve_revisions"
     [ $preserve_timestamp   -gt 0 ] && additional_switches="$additional_switches -z $preserve_timestamp"
-    local gc_command="cvmfs_swissknife gc -r $repository_url         \
-                                          -u $CVMFS_UPSTREAM_STORAGE \
-                                          -n $CVMFS_REPOSITORY_NAME  \
-                                          -k $CVMFS_PUBLIC_KEY       \
-                                          -t ${CVMFS_SPOOL_DIR}/tmp/ \
-                                          $additional_switches"
 
-    local tag_command=""
+    # retrieve the base hash of the repository to be editied
+    local base_hash="xx"
+    local manifest="xx"
+
+    # gather extra information for a stratum0 repository and open a transaction
     if is_stratum0 $name; then
-      local base_hash=$(get_mounted_root_hash $name)
-      tag_command="cvmfs_swissknife tag_empty_bin \
-        -r $CVMFS_UPSTREAM_STORAGE                \
-        -w $CVMFS_STRATUM0                        \
-        -t ${CVMFS_SPOOL_DIR}/tmp                 \
-        -m $new_manifest                          \
-        -p /etc/cvmfs/keys/${name}.pub            \
-        -f $name                                  \
-        -b $base_hash                             \
-        -e $CVMFS_HASH_ALGORITHM"
-    fi
+      base_hash="$(get_mounted_root_hash $name)"
+      manifest="${CVMFS_SPOOL_DIR}/tmp/manifest"
 
-    # do it!
-    if [ $open_transaction -eq 1 ]; then
       trap "close_transaction $name 0" EXIT HUP INT TERM
       open_transaction $name || die "Failed to open transaction for garbage collection"
     fi
 
+    # run the garbage collection
     echo "Running Garbage Collection"
-    $user_shell "$gc_command" || die "Fail! Executed Command: $gc_command"
+    __run_gc $name           \
+             $manifest       \
+             $base_hash      \
+             $repository_url \
+             $dry_run        \
+             $additional_switches || die "Fail ($?)!"
 
+    # sign the result
     if is_stratum0 $name && [ $dry_run -eq 0 ]; then
-      echo "Updating History Database"
-      $user_shell "$tag_command" || die "Fail! Executed Command: $tag_command"
-
       echo "Signing Repository Manifest"
-      sign_manifest $name $new_manifest || die "Fail!"
+      sign_manifest $name $manifest || die "Fail!"
     fi
 
   done
+}
+
+__run_gc() {
+  local name="$1"
+  local manifest="$2"
+  local base_hash="$3"
+  local repository_url="$4"
+  local dry_run="$5"
+  shift 5
+  local additional_switches="$*"
+
+  load_repo_config $name
+
+  # sanity checks
+  is_in_transaction      $name || is_stratum1 $name || return 1
+  is_garbage_collectable $name ||                      return 2
+
+  # do it!
+  local user_shell="$(get_user_shell $name)"
+
+  local gc_command="cvmfs_swissknife gc -r $repository_url         \
+                                        -u $CVMFS_UPSTREAM_STORAGE \
+                                        -n $CVMFS_REPOSITORY_NAME  \
+                                        -k $CVMFS_PUBLIC_KEY       \
+                                        -t ${CVMFS_SPOOL_DIR}/tmp/ \
+                                        $additional_switches"
+  $user_shell "$gc_command" || return 3
+
+  if is_stratum0 $name && [ $dry_run -eq 0 ]; then
+    tag_command="cvmfs_swissknife tag_empty_bin \
+      -r $CVMFS_UPSTREAM_STORAGE                \
+      -w $CVMFS_STRATUM0                        \
+      -t ${CVMFS_SPOOL_DIR}/tmp                 \
+      -m $manifest                              \
+      -p /etc/cvmfs/keys/${name}.pub            \
+      -f $name                                  \
+      -b $base_hash                             \
+      -e $CVMFS_HASH_ALGORITHM"
+    $user_shell "$tag_command" || return 4
+  fi
+
+  return 0
 }
 
 
