add gc -a option

diff --git a/cvmfs/cvmfs_server b/cvmfs/cvmfs_server
--- a/cvmfs/cvmfs_server
+++ b/cvmfs/cvmfs_server
@@ -330,10 +330,11 @@ Supported Commands:
                   Make a new repository snapshot
   gc              [-r number of revisions to preserve]
                   [-t time stamp after which revisions are reserved]
-                  [-l (print deleted objects)] [-L log of deleted objects]
-                  [-f (force)] [-d (dry run)]
-                  <fully qualified repository name>
-                  Remove unreferenced data from garbage collectable repository
+                  [-l print deleted objects] [-L log of deleted objects]
+                  [-f force] [-d dry run]
+                  [-a collect all garbage-collectable repos, log to gc.log |
+                    <fully qualified name> ]
+                  Remove unreferenced data from garbage-collectable repository
   rmfs            [-p(reserve) repo data and keys] [-f don't ask again]
                   <fully qualified name>
                   Remove the repository
@@ -983,6 +984,18 @@ is_stratum0() {
 is_stratum1() {
   local name=$1
   ! is_stratum0 $name
+}
+
+
+# checks if a repository is a replica flagged as being inactive
+#
+# @param name  the name of the repository to be checked
+# @return      0 if it is an inactive replica
+is_inactive_replica() {
+  local name=$1
+  unset CVMFS_REPLICA_ACTIVE # remove previous setting, default is yes
+  load_repo_config $name
+  is_stratum1 $name && [ x"$CVMFS_REPLICA_ACTIVE" = x"no" ]
 }
 
 
@@ -5153,12 +5166,13 @@ cvmfs_server_gc() {
   local preserve_timestamp=0
   local timestamp_threshold=""
   local force=0
+  local all_collectable=0
   local deletion_log=""
   local reconstruct_reflog="0"
 
   # optional parameter handling
   OPTIND=1
-  while getopts "ldr:t:fL:" option
+  while getopts "ldr:t:faL:" option
   do
     case $option in
       l)
@@ -5176,6 +5190,9 @@ cvmfs_server_gc() {
       f)
         force=1
       ;;
+      a)
+        all_collectable=1
+      ;;
       L)
         deletion_log="$OPTARG"
       ;;
@@ -5188,6 +5205,9 @@ cvmfs_server_gc() {
   shift $(($OPTIND-1))
 
   # get repository names
+  if [ $all_collectable -ne 0 ] && [ -z "$@" ]; then
+    set -- '*'
+  fi
   check_parameter_count_for_multiple_repositories $#
   names=$(get_or_guess_multiple_repository_names "$@")
   check_multiple_repository_existence "$names"
@@ -5195,6 +5215,21 @@ cvmfs_server_gc() {
   # parse timestamp (if given)
   if [ ! -z "$timestamp_threshold"  ]; then
     preserve_timestamp="$(date --date "$timestamp_threshold" +%s 2>/dev/null)" || die "Cannot parse time stamp '$timestamp_threshold'"
+  fi
+
+  if [ $all_collectable -ne 0 ]; then
+    # reduce the names to those that are collectable
+    local collectable_names
+    for name in $names; do
+      if ! is_inactive_replica $name && is_garbage_collectable $name; then
+        collectable_names="$collectable_names $name"
+      fi
+    done
+    # the echo gets rid of the leading blank
+    names="`echo $collectable_names`"
+    if [ -z "$names" ]; then
+      die "There are no active garbage-collectable repositories"
+    fi
   fi
 
   [ $preserve_revisions -ge 0 ] && [ $preserve_timestamp -gt 0 ] && die "Please specify either timestamp OR revision thresholds (-r and -t are mutual exclusive)"
@@ -5219,23 +5254,25 @@ cvmfs_server_gc() {
     echo "YOU ARE ABOUT TO DELETE DATA! Are you sure you want to do the following:"
   fi
 
-  local dry_run_msg="no"
-  if [ $dry_run -eq 1 ]; then dry_run_msg="yes"; fi
+  if [ $force -eq 0 ] || [ $all_collectable -eq 0 ]; then
+    local dry_run_msg="no"
+    if [ $dry_run -eq 1 ]; then dry_run_msg="yes"; fi
 
-  local reflog_reconstruct_msg="no"
-  if [ $reconstruct_reflog -eq 1 ]; then reflog_reconstruct_msg="yes"; fi
+    local reflog_reconstruct_msg="no"
+    if [ $reconstruct_reflog -eq 1 ]; then reflog_reconstruct_msg="yes"; fi
 
-  echo "Affected Repositories:         $names"
-  echo "Dry Run (no actual deletion):  $dry_run_msg"
-  echo "Needs Reflog reconstruction:   $reflog_reconstruct_msg"
-  if [ $preserve_revisions -ge 0 ]; then
-    echo "Preserved Legacy Revisions:    $preserve_revisions"
-  fi
-  if [ $preserve_timestamp -gt 0 ]; then
-    echo "Preserve Revisions newer than: $(date -d@$preserve_timestamp +'%x %X')"
-  fi
-  if [ $preserve_revisions -le 0 ] && [ $preserve_timestamp -le 0 ]; then
-    echo "Only the latest revision will be preserved."
+    echo "Affected Repositories:         $names"
+    echo "Dry Run (no actual deletion):  $dry_run_msg"
+    echo "Needs Reflog reconstruction:   $reflog_reconstruct_msg"
+    if [ $preserve_revisions -ge 0 ]; then
+      echo "Preserved Legacy Revisions:    $preserve_revisions"
+    fi
+    if [ $preserve_timestamp -gt 0 ]; then
+      echo "Preserve Revisions newer than: $(date -d@$preserve_timestamp +'%x %X')"
+    fi
+    if [ $preserve_revisions -le 0 ] && [ $preserve_timestamp -le 0 ]; then
+      echo "Only the latest revision will be preserved."
+    fi
   fi
 
   if [ $force -eq 0 ]; then
@@ -5247,6 +5284,56 @@ cvmfs_server_gc() {
   fi
 
   for name in $names; do
+
+    if [ $all_collectable -eq 0 ]; then
+      __do_gc_cmd "$name"                       \
+                  "$dry_run"                    \
+                  "$list_deleted_objects"       \
+                  "$preserve_revisions"         \
+                  "$preserve_timestamps"        \
+                  "$deletion_log"
+    else
+      local log=/var/log/cvmfs/gc.log
+
+      (
+      echo
+      echo "Starting $name at `date`"
+      # Work around the errexit (that is, set -e) misfeature of being
+      #  disabled whenever the exit code is to be checked.
+      # See https://lists.gnu.org/archive/html/bug-bash/2012-12/msg00093.html
+      set +e
+      (set -e
+      __do_gc_cmd "$name"                       \
+                  "$dry_run"                    \
+                  "$list_deleted_objects"       \
+                  "$preserve_revisions"         \
+                  "$preserve_timestamps"        \
+                  "$deletion_log"
+      )
+      if [ $? != 0 ]; then
+        echo "ERROR from cvmfs_server gc!" >&2
+      fi
+      echo "Finished $name at `date`"
+      ) >> $log 2>&1
+
+      # Always return success because this is used from cron and we
+      #  don't want cron sending an email every time something fails.
+      # Errors will be in the log.
+    fi
+  done
+}
+
+# this is used when gc is invoked from the cvmfs_server command line
+__do_gc_cmd()
+{
+  local name="$1"
+  local dry_run="$2"
+  local list_deleted_objects="$3"
+  local preserve_revisions="$4"
+  local preserve_timestamps="$5"
+  local deletion_log="$6"
+
+  # leave extra layer of indent for now to better show diff with previous
 
     load_repo_config $name
 
@@ -5292,8 +5379,6 @@ cvmfs_server_gc() {
       fi
     fi
 
-    to_syslog_for_repo $name "started manual garbage collection"
-
     local reconstruct_this_reflog=0
     if ! has_reference_log $name; then
       reconstruct_this_reflog=1
@@ -5316,7 +5401,7 @@ cvmfs_server_gc() {
     if is_stratum0 $name && [ $dry_run -eq 0 ]; then
       echo "Signing Repository Manifest"
       if ! sign_manifest $name $manifest; then
-        to_syslog_for_repo $name "failed to sign manifest after manual garbage collection"
+        to_syslog_for_repo $name "failed to sign manifest after garbage collection"
         die "Fail!"
       fi
 
@@ -5324,12 +5409,10 @@ cvmfs_server_gc() {
       trap - EXIT HUP INT TERM
       close_transaction $name 0
     fi
-
-    to_syslog_for_repo $name "successfully finished manual garbage collection"
-
-  done
 }
 
+# this is used for both auto-gc (after publish or snapshot) and non-auto-gc
+#   (when invoked from the cvmfs_server command line)
 __run_gc() {
   local name="$1"
   local repository_url="$2"
@@ -5672,13 +5755,12 @@ EOF
     # get repository information
     local repodir="${replica%/*}"
     repo="${repodir##*/}"
-    unset CVMFS_REPLICA_ACTIVE # remove previous setting, default is yes
-    load_repo_config $repo
 
-    if [ "$CVMFS_REPLICA_ACTIVE" = "no" ]; then
+    if is_inactive_replica $repo; then
       continue
     fi
 
+    load_repo_config $repo
     local upstream=$CVMFS_UPSTREAM_STORAGE
     local snapshot_time=0
     if is_local_upstream $upstream; then
