Fixing merge conflict

diff --git a/cvmfs/cvmfs_server b/cvmfs/cvmfs_server
--- a/cvmfs/cvmfs_server
+++ b/cvmfs/cvmfs_server
@@ -2550,7 +2550,6 @@ mkfs() {
 
   # create system-wide configuration
   echo -n "Creating Configuration Files... "
-<<<<<<< HEAD
   create_config_files_for_new_repository "$name"        \
                                          "$upstream"    \
                                          "$stratum0"    \
@@ -2558,10 +2557,10 @@ mkfs() {
                                          "$unionfs"     \
                                          "$hash_algo"   \
                                          "$autotagging" \
-                                         "$garbage_collectable" || die "fail"
-=======
-  create_config_files_for_new_repository $name $upstream $stratum0 $cvmfs_user $unionfs $hash_algo $autotagging $garbage_collectable $compression_alg || die "fail"
->>>>>>> 0f2a56849e792a4ccfa448ea3ca97028b038e9b8
+                                         "$garbage_collectable" \
+                                         "$compression_alg" \
+                                         || die "fail"
+
   if is_local_upstream $upstream; then
     reload_apache > /dev/null
   fi
