cvmfs/cvmfs_config : Added a regularcheck() argument and function for cvmfs_fsck to check consistency of all the mounted files

diff --git a/cvmfs/cvmfs_config b/cvmfs/cvmfs_config
--- a/cvmfs/cvmfs_config
+++ b/cvmfs/cvmfs_config
@@ -90,6 +90,7 @@ cvmfs_config_usage() {
  echo "  umount"
  echo "  wipecache"
  echo "  bugreport"
+ echo "  regularcheck"
 }
 
 
@@ -1117,6 +1118,25 @@ cvmfs_bugreport() {
    echo "JIRA bug report to https://sft.its.cern.ch/jira/browse/CVM"
 }
 
+cvmfs_regularcheck() {
+  
+  if ! cvmfs_readconfig; then
+    echo "Failed to read CernVM-FS configuration"
+    return 1
+  fi
+
+  local repo_list
+  if [ "x$CVMFS_REPOSITORIES" != "x" ]; then
+    repo_list=`echo $CVMFS_REPOSITORIES | sed 's/,/ /g'`
+  fi
+
+  local repo
+  for repo in $repo_list
+  do
+     sudo /usr/bin/cvmfs_fsck ${CVMFS_CACHE_BASE}/${repo}
+  done
+}
+
 
 list_mounts() {
   mount -t $fuse_fs_type | grep "^cvmfs2[[:space:]]"
@@ -1564,6 +1584,16 @@ case "$1" in
      cvmfs_bugreport $@
      RETVAL=$?
      ;;
+     
+  regularcheck)
+    if [`id -u` -ne 0]; then
+      echo "root privileges required"
+      exit 1
+    fi
+    shift 1
+    cvmfs_regularcheck
+    RETVAL=$?
+    ;;
 
    *)
      cvmfs_config_usage
