put/get interface for server tools (work in progress)

diff --git a/cvmfs/cvmfs_server b/cvmfs/cvmfs_server
--- a/cvmfs/cvmfs_server
+++ b/cvmfs/cvmfs_server
@@ -152,22 +152,28 @@ publish() {
   publish_before_hook $name
   sudo /bin/mount -o remount,ro /cvmfs/$name
   local base_hash=$(attr -qg root_hash /var/spool/cvmfs/${name}/rdonly)
+   
   $user_shell "cvmfs_sync -p -u /cvmfs/$name \
     -s /var/spool/cvmfs/${name}/scratch \
     -c /var/spool/cvmfs/${name}/rdonly \
-    -r /var/spool/cvmfs/${name}/tmp \
+    -t /var/spool/cvmfs/${name}/tmp \
+    -r local:/srv/cvmfs/${name} \
     -b $base_hash \
     -x /var/spool/cvmfs/${name}/paths \
     -y /var/spool/cvmfs/${name}/hashes \
+    -w http://localhost/cvmfs/$name \
     $CVMFS_PUBLISH_OPTIONS" || die "Synchronization failed"
   $user_shell "cvmfs_sign \
     -c /etc/cvmfs/keys/${name}.crt \
     -k /etc/cvmfs/keys/${name}.key \
     -n $name \
-    /srv/cvmfs/${name}/pub/catalogs/.cvmfspublished" || die "Signing failed"
+    -t /var/spool/cvmfs/${name}/tmp \
+    -r local:/srv/cvmfs/${name} \
+    -u http://localhost/cvmfs/$name" || die "Signing failed"
   sudo umount /cvmfs/$name
   sudo umount /var/spool/cvmfs/${name}/rdonly
   rm -rf /var/spool/cvmfs/${name}/scratch
+  rm -rf /var/spool/cvmfs/${name}/tmp/*
   $user_shell "mkdir /var/spool/cvmfs/${name}/scratch"
   sudo mount /var/spool/cvmfs/${name}/rdonly > /dev/null
   sudo mount /cvmfs/$name
@@ -284,7 +290,9 @@ EOF
   cvmfs_sign -c /etc/cvmfs/keys/${name}.crt \
     -k /etc/cvmfs/keys/${name}.key \
     -n $name \
-    ${repository_dir}/.cvmfspublished > /dev/null
+    -t $temp_dir \
+    -r local:$repository_dir \
+    -u http://localhost/cvmfs/$name > /dev/null
   echo "done"
 
   echo -n "Mounting CernVM-FS Storage... "
