shield against interleaving publishes

diff --git a/cvmfs/cvmfs_server b/cvmfs/cvmfs_server
--- a/cvmfs/cvmfs_server
+++ b/cvmfs/cvmfs_server
@@ -535,6 +535,23 @@ close_transaction() {
   rmdir ${CVMFS_SPOOL_DIR}/in_transaction
 }
 
+# checks if a repository is currently runing a publish procedure
+#
+# @param name  the repository name to be checked
+# @return      0 if a publishing procedure is running
+is_publishing() {
+  local name=$1
+  load_repo_config $name
+  [ -d ${CVMFS_SPOOL_DIR}/is_publishing ]
+}
+
+publishing_lock() {
+  local name=$1
+  load_repo_config $name
+  mkdir ${CVMFS_SPOOL_DIR}/is_publishing > /dev/null 2>&1 || die "Failed to acquire publishing lock"
+  trap "rmdir ${CVMFS_SPOOL_DIR}/is_publishing > /dev/null 2>&1" 0
+}
+
 
 # checks if a user exists in the system
 #
@@ -2239,7 +2256,8 @@ abort() {
   for name in $names; do
 
     # sanity checks
-    is_stratum0 $name || { echo "Repository $name is not a stratum 0 repository"; retcode=1; continue; }
+    is_stratum0 $name   || { echo "Repository $name is not a stratum 0 repository"; retcode=1; continue; }
+    is_publishing $name && { echo "Repository $name is currently published (aborting abort)"; retcode=1; continue; }
 
     # get repository information
     load_repo_config $name
@@ -2360,7 +2378,8 @@ publish() {
   for name in $names; do
 
     # sanity checks
-    is_stratum0 $name || die "This is not a stratum 0 repository"
+    is_stratum0 $name   || die "This is not a stratum 0 repository"
+    is_publishing $name && die "Another publish process is active for $name"
 
     # get repository information
     load_repo_config $name
@@ -2412,6 +2431,7 @@ publish() {
     [ $(whoami) != $user ] && user_shell="sudo -E -H -u $user sh -c"
 
     publish_before_hook $name
+    publishing_lock $name
     cvmfs_suid_helper lock $name
     local base_hash=$(attr -qg root_hash ${spool_dir}/rdonly)
     local log_level=
@@ -2520,7 +2540,8 @@ rollback() {
 
   # sanity checks
   check_repository_existence $name || die "The repository $name does not exist"
-  is_stratum0 $name || die "This is not a stratum 0 repository"
+  is_stratum0 $name                || die "This is not a stratum 0 repository"
+  is_publishing $name              && die "Repository $name is currently being published"
 
   # get repository information
   . /etc/cvmfs/repositories.d/$name/server.conf
@@ -2550,6 +2571,7 @@ rollback() {
   [ $(whoami) != $user ] && user_shell="sudo -E -H -u $user sh -c"
 
   publish_before_hook
+  publishing_lock $name
   cvmfs_suid_helper lock $name
   local base_hash=$(attr -qg root_hash ${spool_dir}/rdonly)
 
