still add cvmfs user to fuse group

diff --git a/cvmfs/cvmfs_config b/cvmfs/cvmfs_config
--- a/cvmfs/cvmfs_config
+++ b/cvmfs/cvmfs_config
@@ -279,13 +279,11 @@ cvmfs_setup() {
     fi
   fi
 
-  if [ $nouser -eq 0 ]; then
-    # if group fuse exists, add user cvmfs
-    if check_group "fuse"; then
-      if ! add_user_to_group_fuse; then
-        echo "Cannot add user cvmfs to group fuse"
-        exit 1
-      fi
+  # if group fuse exists, add user cvmfs
+  if check_group "fuse"; then
+    if ! add_user_to_group_fuse; then
+      echo "Cannot add user cvmfs to group fuse"
+      exit 1
     fi
   fi
 
