put/get interface for server tools (work in progress)

diff --git a/cvmfs/cvmfs_server b/cvmfs/cvmfs_server
--- a/cvmfs/cvmfs_server
+++ b/cvmfs/cvmfs_server
@@ -56,34 +56,45 @@ create_cert() {
 
 
 create_whitelist() {
-   local name=$1
-   local user=$2
-   local whitelist="/srv/cvmfs/$name/.cvmfswhitelist"
+  local name=$1
+  local user=$2
+  local upstream=$3
+  local temp_dir=$4
 
-   echo -n "Signing 30 day whitelist with master key... "
-   echo `date -u "+%Y%m%d%H%M%S"` > ${whitelist}.unsigned
-   echo "E`date -u --date='next month' "+%Y%m%d%H%M%S"`" >> ${whitelist}.unsigned
-   echo "N$name" >> ${whitelist}.unsigned
-   openssl x509 -fingerprint -sha1 -in /etc/cvmfs/keys/${name}.crt | grep "SHA1 Fingerprint" | sed 's/SHA1 Fingerprint=//' >> ${whitelist}.unsigned
+  local whitelist
+  local repository_dir=$(get_local_upstream $upstream)
+  if [ x"$repository_dir" != x ]; then
+    whitelist=${repository_dir}/.cvmfswhitelist
+  else
+    whitelist=${temp_dir}/whitelist
+  fi
 
-   local sha1; sha1=`openssl sha1 < ${whitelist}.unsigned | head -c40`
-   echo "--" >> ${whitelist}.unsigned
-   echo $sha1 >> ${whitelist}.unsigned
-   echo -n $sha1 > ${whitelist}.sha1
-   openssl rsautl -inkey /etc/cvmfs/keys/${name}.masterkey -sign -in ${whitelist}.sha1 -out ${whitelist}.signature
-   cat ${whitelist}.unsigned ${whitelist}.signature > $whitelist
-   chown $user $whitelist
+  echo -n "Signing 30 day whitelist with master key... "
+  echo `date -u "+%Y%m%d%H%M%S"` > ${whitelist}.unsigned
+  echo "E`date -u --date='next month' "+%Y%m%d%H%M%S"`" >> ${whitelist}.unsigned
+  echo "N$name" >> ${whitelist}.unsigned
+  openssl x509 -fingerprint -sha1 -in /etc/cvmfs/keys/${name}.crt | grep "SHA1 Fingerprint" | sed 's/SHA1 Fingerprint=//' >> ${whitelist}.unsigned
 
-   rm -f ${whitelist}.unsigned ${whitelist}.signature ${whitelist}.sha1
-   echo "done"
+  local sha1; sha1=`openssl sha1 < ${whitelist}.unsigned | head -c40`
+  echo "--" >> ${whitelist}.unsigned
+  echo $sha1 >> ${whitelist}.unsigned
+  echo -n $sha1 > ${whitelist}.sha1
+  openssl rsautl -inkey /etc/cvmfs/keys/${name}.masterkey -sign -in ${whitelist}.sha1 -out ${whitelist}.signature
+  cat ${whitelist}.unsigned ${whitelist}.signature > $whitelist
+  chown $user $whitelist
+
+  rm -f ${whitelist}.unsigned ${whitelist}.signature ${whitelist}.sha1
+  echo "done"
+  
+  [ x"$repository_dir" == x ] && echo "Move $whitelist to ${upstream}/.cvmfswhitelist" || true
 }
 
 
 get_expiry() {
   local name=$1
-  local whitelist="/srv/cvmfs/$name/.cvmfswhitelist"
-
-  local expires=$(head -2 $whitelist| tail -1 | tail -c15)
+  local stratum0=$2
+  
+  local expires=$(curl $stratum0/.cvmfswhitelist 2>/dev/null | head -2 | tail -1 | tail -c15)
   local year=$(echo $expires | head -c4)
   local month=$(echo $expires | head -c6 | tail -c2)
   local day=$(echo $expires | head -c8 | tail -c2)
@@ -96,6 +107,17 @@ get_expiry() {
 }
 
 
+get_local_upstream() {
+  local upstream=$1
+  
+  if [ x$(echo "$upstream" | cut -d: -f1) = x"local" ]; then
+    echo "$(echo $upstream | cut -d: -f2)"
+  else
+    echo ""
+  fi
+}
+
+
 reload_apache() {
    echo -n "Reloading Apache... "
    /sbin/service httpd reload > /dev/null
@@ -105,12 +127,13 @@ reload_apache() {
 
 transaction() {
   local name=$1
+  local spool_dir=$2
 
-  [ -f /var/spool/cvmfs/${name}/in_transaction ] && die "Already in a transaction"
+  [ -f ${spool_dir}/in_transaction ] && die "Already in a transaction"
 
   transaction_before_hook $name
   sudo mount -o remount,rw /cvmfs/$name
-  touch /var/spool/cvmfs/${name}/in_transaction
+  touch ${spool_dir}/in_transaction
   transaction_after_hook $name
 }
 
@@ -118,8 +141,9 @@ transaction() {
 abort() {
   local name=$1
   local user=$2
+  local spool_dir=$3
 
-  [ -f /var/spool/cvmfs/${name}/in_transaction ] || die "Not in a transaction"
+  [ -f ${spool_dir}/in_transaction ] || die "Not in a transaction"
   fuser -m /cvmfs/$name > /dev/null 2>&1 && die "Open file descriptors on $name"
 
   reply=n
@@ -131,10 +155,10 @@ abort() {
 
   abort_before_hook $name
   sudo umount /cvmfs/$name
-  sudo rm -rf /var/spool/cvmfs/${name}/scratch
+  sudo rm -rf ${spool_dir}/scratch
   $user_shell "mkdir /var/spool/cvmfs/${name}/scratch"
   sudo mount /cvmfs/$name
-  rm -f /var/spool/cvmfs/${name}/in_transaction
+  rm -f ${spool_dir}/in_transaction
   abort_after_hook $name
 }
 
@@ -142,8 +166,11 @@ abort() {
 publish() {
   local name=$1
   local user=$2
+  local spool_dir=$3
+  local stratum0=$4
+  local upstream=$5
 
-  [ -f /var/spool/cvmfs/${name}/in_transaction ] || die "Not in a transaction"
+  [ -f ${spool_dir}/in_transaction ] || die "Not in a transaction"
   fuser -m /cvmfs/$name > /dev/null 2>&1 && die "Open file descriptors on $name"
 
   local user_shell="sh -c"
@@ -151,44 +178,51 @@ publish() {
 
   publish_before_hook $name
   sudo /bin/mount -o remount,ro /cvmfs/$name
-  local base_hash=$(attr -qg root_hash /var/spool/cvmfs/${name}/rdonly)
+  local base_hash=$(attr -qg root_hash ${spool_dir}/rdonly)
    
   $user_shell "cvmfs_sync -p -u /cvmfs/$name \
-    -s /var/spool/cvmfs/${name}/scratch \
-    -c /var/spool/cvmfs/${name}/rdonly \
-    -t /var/spool/cvmfs/${name}/tmp \
-    -r local:/srv/cvmfs/${name} \
+    -s ${spool_dir}/scratch \
+    -c ${spool_dir}/rdonly \
+    -t ${spool_dir}/tmp \
+    -r $upstream \
     -b $base_hash \
-    -x /var/spool/cvmfs/${name}/paths \
-    -y /var/spool/cvmfs/${name}/hashes \
-    -w http://localhost/cvmfs/$name \
+    -x ${spool_dir}/paths \
+    -y ${spool_dir}/hashes \
+    -w $stratum0 \
     $CVMFS_PUBLISH_OPTIONS" || die "Synchronization failed"
   $user_shell "cvmfs_sign \
     -c /etc/cvmfs/keys/${name}.crt \
     -k /etc/cvmfs/keys/${name}.key \
     -n $name \
-    -t /var/spool/cvmfs/${name}/tmp \
-    -r local:/srv/cvmfs/${name} \
-    -u http://localhost/cvmfs/$name" || die "Signing failed"
+    -t ${spool_dir}/tmp \
+    -r $upstream \
+    -u $stratum0" || die "Signing failed"
   sudo umount /cvmfs/$name
-  sudo umount /var/spool/cvmfs/${name}/rdonly
-  sudo rm -rf /var/spool/cvmfs/${name}/scratch
-  rm -rf /var/spool/cvmfs/${name}/tmp/*
-  $user_shell "mkdir /var/spool/cvmfs/${name}/scratch"
-  sudo mount /var/spool/cvmfs/${name}/rdonly > /dev/null
+  sudo umount ${spool_dir}/rdonly
+  sudo rm -rf ${spool_dir}/scratch
+  rm -rf ${spool_dir}/tmp/*
+  $user_shell "mkdir ${spool_dir}/scratch"
+  sudo mount ${spool_dir}/rdonly > /dev/null
   sudo mount /cvmfs/$name
-  rm -f /var/spool/cvmfs/${name}/in_transaction
+  rm -f ${spool_dir}/in_transaction
   publish_after_hook $name
 }
 
 
 mkfs() {
   local name=$1
-  local scratch_dir="/var/spool/cvmfs/${name}/scratch"
-  local rdonly_dir="/var/spool/cvmfs/${name}/rdonly"
-  local temp_dir="/var/spool/cvmfs/${name}/tmp"
-  local repository_dir="/srv/cvmfs/${name}"
+  local stratum0=$2
+  local upstream=$3
+  
+  local spool_dir="/var/spool/cvmfs/${name}"
+  local scratch_dir="${spool_dir}/scratch"
+  local rdonly_dir="${spool_dir}/rdonly"
+  local temp_dir="${spool_dir}/tmp"
+  local pipe_paths="${spool_dir}/paths"
+  local pipe_hashes="${spool_dir}/hashes"
+  local repository_dir=$(get_local_upstream $upstream)
 
+  # Sanity checks
   [ $(id -u) -ne 0 ] && die "Only root can create a new repository"
   modprobe aufs || die "aufs kernel module missing"
   cat /proc/mounts | grep -q "^/etc/auto.cvmfs /cvmfs " && die "Autofs on /cvmfs has to be disabled"
@@ -201,21 +235,32 @@ mkfs() {
   echo -n "Creating configuration files... "
   mkdir -p /etc/cvmfs/repositories.d/${name}
   cat > /etc/cvmfs/repositories.d/${name}/server.conf << EOF
-# Created by cvmfs_server.  Don't touch.
+# Created by cvmfs_server.
 CVMFS_REPOSITORY_NAME=$name
 CVMFS_USER=$cvmfs_user
 CVMFS_UNION_DIR=/cvmfs/$name
-CVMFS_REPOSITORY_DIR=$repository_dir
-CVMFS_SCRATCH_DIR=$scratch_dir
-CVMFS_RDONLY_MOUNTPOINT=$rdonly_dir
-CVMFS_TEMP_DIR=$repository_dir
+CVMFS_SPOOL_DIR=$spool_dir
+CVMFS_STRATUM0=$stratum0
+CVMFS_UPSTREAM_STORAGE=$upstream
 EOF
   cat > /etc/httpd/conf.d/cvmfs.${name}.conf << EOF
 # Created by cvmfs_server.  Don't touch.
-# Translation URL to real pathname
-Alias /cvmfs/$name ${repository_dir}
 # For pushing files to the worker nodes
 Alias /fanout/cvmfs/$name /cvmfs/$name
+<Directory "/cvmfs/$name">
+    Options -MultiViews
+    AllowOverride All
+    Order allow,deny
+    Allow from all
+
+    EnableMMAP Off
+    EnableSendFile Off
+</Directory>
+EOF
+  if [ x"$stratum0" = x"http://localhost/cvmfs/$name" ]; then
+    cat >> /etc/httpd/conf.d/cvmfs.${name}.conf << EOF
+# Translation URL to real pathname
+Alias /cvmfs/$name ${repository_dir}
 <Directory "${repository_dir}">
     Options -MultiViews
     AllowOverride All
@@ -235,19 +280,11 @@ Alias /fanout/cvmfs/$name /cvmfs/$name
     ExpiresByType text/html "access plus 5 minutes"
     ExpiresByType application/x-cvmfs "access plus 1 minutes"
 </Directory>
-<Directory "/cvmfs/$name">
-    Options -MultiViews
-    AllowOverride All
-    Order allow,deny
-    Allow from all
-
-    EnableMMAP Off
-    EnableSendFile Off
-</Directory>
 EOF
+  fi
   cat > /etc/cvmfs/config.d/${name}.conf << EOF
 # Created by cvmfs_server.  Don't touch.
-CVMFS_SERVER_URL=http://localhost/cvmfs/$name
+CVMFS_SERVER_URL=$stratum0
 CVMFS_HTTP_PROXY=DIRECT
 CVMFS_PUBLIC_KEY=/etc/cvmfs/keys/${name}.pub
 CVMFS_STRICT_MOUNT=no
@@ -256,10 +293,10 @@ EOF
 $cvmfs_user localhost = NOPASSWD: /bin/mount -o remount\,ro /cvmfs/$name # added by CernVM-FS for $name
 $cvmfs_user localhost = NOPASSWD: /bin/mount -o remount\,rw /cvmfs/$name # added by CernVM-FS for $name
 $cvmfs_user localhost = NOPASSWD: /bin/umount /cvmfs/$name # added by CernVM-FS for $name
-$cvmfs_user localhost = NOPASSWD: /bin/umount /var/spool/cvmfs/${name}/rdonly # added by CernVM-FS for $name
-$cvmfs_user localhost = NOPASSWD: /bin/mount /var/spool/cvmfs/${name}/rdonly # added by CernVM-FS for $name
+$cvmfs_user localhost = NOPASSWD: /bin/umount $rdonly_dir # added by CernVM-FS for $name
+$cvmfs_user localhost = NOPASSWD: /bin/mount $rdonly_dir # added by CernVM-FS for $name
 $cvmfs_user localhost = NOPASSWD: /bin/mount /cvmfs/$name # added by CernVM-FS for $name
-$cvmfs_user localhost = NOPASSWD: /bin/rm -rf /var/spool/cvmfs/${name}/scratch # added by CernVM-FS for $name
+$cvmfs_user localhost = NOPASSWD: /bin/rm -rf $scratch_dir # added by CernVM-FS for $name
 EOF
   echo "done"
 
@@ -268,32 +305,32 @@ EOF
   create_cert $name $cvmfs_user
 
   echo -n "Create CernVM-FS Storage... "
-  mkdir -p /cvmfs/$name \
-    ${repository_dir}/data \
-    $scratch_dir $rdonly_dir $temp_dir
-  local i=0
-  while [ $i -lt 256 ]
-  do
-    mkdir ${repository_dir}/data/$(printf "%02x" $i)
-    i=$(($i+1))
-  done
-  mkfifo -m 0660 /var/spool/cvmfs/${name}/paths \
-    /var/spool/cvmfs/${name}/hashes
-  chown -R $cvmfs_user /cvmfs/$name $repository_dir /var/spool/cvmfs/$name
+  mkdir -p /cvmfs/$name $scratch_dir $rdonly_dir $temp_dir
+  mkfifo -m 0660 $pipe_paths $pipe_hashes
+  if [ x"$repository_dir" != x ]; then
+    mkdir -p ${repository_dir}/data
+    local i=0
+    while [ $i -lt 256 ]
+    do
+      mkdir ${repository_dir}/data/$(printf "%02x" $i)
+      i=$(($i+1))
+    done
+  fi
+  chown -R $cvmfs_user /cvmfs/$name $spool_dir $repository_dir
   reload_apache > /dev/null
   echo "done"
   
   echo -n "Create Initial Repository... "
-  create_whitelist $name $cvmfs_user > /dev/null
+  create_whitelist $name $cvmfs_user $upstream $temp_dir > /dev/null
   cvmfs_sync -n \
     -t $temp_dir \
-    -r local:$repository_dir > /dev/null
+    -r $upstream > /dev/null
   cvmfs_sign -c /etc/cvmfs/keys/${name}.crt \
     -k /etc/cvmfs/keys/${name}.key \
     -n $name \
     -t $temp_dir \
-    -r local:$repository_dir \
-    -u http://localhost/cvmfs/$name > /dev/null
+    -r $upstream \
+    -u $stratum0 > /dev/null
   chown -R $cvmfs_user $repository_dir
   echo "done"
 
@@ -307,11 +344,11 @@ EOF
   echo "done"
 
   echo -n "Starting services... "
-  transaction $name > /dev/null
+  transaction $name $spool_dir > /dev/null
   echo "New CernVM-FS repository for $name" > /cvmfs/${name}/new_repository
   CVMFS_PUBLISH_OPTIONS="-z"
-  publish $name $cvmfs_user
-  echo "done"
+  publish $name $cvmfs_user $spool_dir $stratum0 $upstream
+  cat $rdonly_dir/new_repository
 
   echo "\
 
@@ -325,20 +362,29 @@ If you go for production, backup you software signing keys in /etc/cvmfs/keys/!"
 
 rmfs() {
   local name=$1
+  local spool_dir=$2
+  local upstream=$3
 
   [ $(id -u) -ne 0 ] && die "Only root can remove a repository"
+  [ x"$spool_dir" = x ] && die "Spool directory undefined"
+  [ x"$upstream" = x ] && die "Upstream storage undefined"
 
   echo -n "Unmounting CernVM-FS Area... "
   sed -i -e "/added by CernVM-FS for ${name}/d" /etc/fstab
   mount | grep -q " /cvmfs/$name " && umount /cvmfs/$name
-  mount | grep -q " /var/spool/cvmfs/$name/rdonly " && umount /var/spool/cvmfs/$name/rdonly
+  mount | grep -q " ${spool_dir}/rdonly " && umount ${spool_dir}/rdonly
   echo "done"
 
-  echo -n "Removing repository storage... "
-  rm -rf /srv/cvmfs/${name} \
-         /var/spool/cvmfs/$name \
-         /cvmfs/$name
-  echo "done"
+  echo -n "Removing spool area... "
+  rm -rf $spool_dir /cvmfs/$name
+  echo done
+  
+  local repository_dir=$(get_local_upstream $upstream)
+  if [ "x"$repository_dir != x ]; then
+    echo -n "Removing repository storage... "
+    rm -rf $repository_dir
+    echo "done"
+  fi
 
   echo -n "Removing keys and configuration... "
   rm -f /etc/cvmfs/keys/$name.masterkey \
@@ -361,16 +407,17 @@ rmfs() {
 
 info() {
   local name=$1
+  local stratum0=$2
 
   echo "Repository name: $name"
-  get_expiry $name
+  get_expiry $name $stratum0
   echo
 
   echo "\
 Client configuration:
 Add $name to CVMFS_REPOSITORIES in /etc/cvmfs/default.local
 Create /etc/cvmfs/config.d/${name}.conf and set
-  CVMFS_SERVER_URL=http://`hostname`/cvmfs/$name
+  CVMFS_SERVER_URL=$stratum0
   CVMFS_PUBLIC_KEY=/etc/cvmfs/keys/${name}.pub
 Copy /etc/cvmfs/keys/${name}.pub to the client"
 }
@@ -385,14 +432,15 @@ usage() {
    echo "\
 CernVM-FS Server Tool
 Commands:
-  mkfs <fully qualified name>: Creates a new repository with a given name
-  rmfs: Removes the repository
-  resign: Re-signs the 30 day whitelist
-  info: Prints summary about the repository
-  list: List available repositories
+  mkfs <fully qualified name> [-w stratum0 url] [-u upstream storage]: 
+               Create a new repository with a given name
+  rmfs:        Remove the repository
+  resign:      Re-sign the 30 day whitelist
+  info:        Print summary about the repository
+  list:        List available repositories
   transaction: Start to edit a repository
-  abort: Abort transaction and return to the state before
-  publish: Makes a new repository snapshot
+  abort:       Abort transaction and return to the state before
+  publish:     Make a new repository snapshot
 
 Note: If multiple repositories are maintained, the repository name must follow
 the command."
@@ -425,41 +473,63 @@ case $1 in
       usage
       exit 2
     fi
-    mkfs $CVMFS_REPOSITORY_NAME
-   ;;
+    # Stratum 0, upstream storage
+    STRATUM0="http://localhost/cvmfs/$CVMFS_REPOSITORY_NAME"
+    UPSTREM="local:/srv/cvmfs/$CVMFS_REPOSITORY_NAME"
+    shift 2
+    while getopts "w:u:" OPTION
+    do
+      case $OPTION in
+        w)
+          STRATUM0=$OPTARG
+        ;;
+        u)
+          UPSTREM=$OPTARG
+        ;;
+        ?)
+          echo "Invalid option"
+          exit 1
+        ;;
+      esac
+    done
+    mkfs $CVMFS_REPOSITORY_NAME $STRATUM0 $UPSTREM 
+    ;;
   rmfs)
     [ x"$CVMFS_REPOSITORY_NAME" = x ] && die "Which repository?"
     reply=n
     read -p "You are about to WIPE OUT THE CERNVM-FS REPOSITORY INCLUDING SIGNING KEYS!  Are you sure (y/n)? " reply
     if [ "$reply" = "y" ]; then
-      rmfs $CVMFS_REPOSITORY_NAME
+      . /etc/cvmfs/repositories.d/${CVMFS_REPOSITORY_NAME}/server.conf
+      rmfs $CVMFS_REPOSITORY_NAME $CVMFS_SPOOL_DIR $CVMFS_UPSTREAM_STORAGE
     fi
   ;;
   resign)
     [ x"$CVMFS_REPOSITORY_NAME" = x ] && die "Which repository?"
     . /etc/cvmfs/repositories.d/${CVMFS_REPOSITORY_NAME}/server.conf
-    create_whitelist $CVMFS_REPOSITORY_NAME $CVMFS_USER
+    create_whitelist $CVMFS_REPOSITORY_NAME $CVMFS_USER $CVMFS_STRATUM0 ${CVMFS_SPOOL_DIR}/tmp
   ;;
   info)
     [ x"$CVMFS_REPOSITORY_NAME" = x ] && die "Which repository"
-    info $CVMFS_REPOSITORY_NAME
+    . /etc/cvmfs/repositories.d/${CVMFS_REPOSITORY_NAME}/server.conf
+    info $CVMFS_REPOSITORY_NAME $CVMFS_STRATUM0
   ;;
   list)
     list_repositories
   ;;
   transaction)
     [ x"$CVMFS_REPOSITORY_NAME" = x ] && die "Which repository"
-    transaction $CVMFS_REPOSITORY_NAME
+    . /etc/cvmfs/repositories.d/${CVMFS_REPOSITORY_NAME}/server.conf
+    transaction $CVMFS_REPOSITORY_NAME $CVMFS_SPOOL_DIR
   ;;
   abort)
     [ x"$CVMFS_REPOSITORY_NAME" = x ] && die "Which repository"
     . /etc/cvmfs/repositories.d/${CVMFS_REPOSITORY_NAME}/server.conf
-    abort $CVMFS_REPOSITORY_NAME $CVMFS_USER
+    abort $CVMFS_REPOSITORY_NAME $CVMFS_USER $CVMFS_SPOOL_DIR
   ;;
   publish)
     [ x"$CVMFS_REPOSITORY_NAME" = x ] && die "Which repository"
     . /etc/cvmfs/repositories.d/${CVMFS_REPOSITORY_NAME}/server.conf
-    publish $CVMFS_REPOSITORY_NAME $CVMFS_USER
+    publish $CVMFS_REPOSITORY_NAME $CVMFS_USER $CVMFS_SPOOL_DIR $CVMFS_STRATUM0 $CVMFS_UPSTREAM_STORAGE
   ;;
   *)
     usage
