Add update-geodb command, and call it from add-replica, snapshot, and migrate

diff --git a/cvmfs/cvmfs_server b/cvmfs/cvmfs_server
--- a/cvmfs/cvmfs_server
+++ b/cvmfs/cvmfs_server
@@ -25,6 +25,15 @@ export LANG=C
 #                                                                              #
 ################################################################################
 
+# Configuration variables for update-geodb -l.  May be overridden in
+#   /etc/cvmfs/cvmfs_server_hooks.sh or per-repo replica.conf.
+# Default settings will attempt to update from cvmfs_server snapshot 
+#   once every 4 weeks in the 10 o'clock hour of Tuesday.
+CVMFS_UPDATEGEO_DAY=2	# Weekday of update, 0-6 where 0 is Sunday, default Tuesday
+CVMFS_UPDATEGEO_HOUR=10	# First hour of day for update, 0-23, default 10am
+CVMFS_UPDATEGEO_MINDAYS=25 # Minimum days between update attempts
+CVMFS_UPDATEGEO_MAXDAYS=100 # Maximum days old before considering it an error
+
 
 # setup server hooks: no-ops (overrideable by /etc/cvmfs/cvmfs_server_hooks.sh)
 transaction_before_hook() { :; }
@@ -81,7 +90,6 @@ CVMFS_DEFAULT_AVG_CHUNK_SIZE=8388608
 CVMFS_DEFAULT_MAX_CHUNK_SIZE=16777216
 CVMFS_DEFAULT_CATALOG_ENTRY_WARN_THRESHOLD=500000
 
-
 ################################################################################
 #                                                                              #
 #                              Utility Functions                               #
@@ -110,7 +118,7 @@ is_subcommand() {
   local subcommand="$1"
   local supported_commands="mkfs add-replica import publish rollback rmfs alterfs \
     resign list info list-tags lstags check transaction abort snapshot skeleton \
-    migrate list-catalogs"
+    migrate list-catalogs update-geodb"
 
   for possible_command in $supported_commands; do
     if [ x"$possible_command" = x"$subcommand" ]; then
@@ -225,6 +233,8 @@ Supported Commands:
   migrate       <fully qualified name>
                 Migrates a repository to the current version of CernVM-FS
   list          List available repositories
+  update-geodb	[-l update lazily based on CVMFS_UPDATEGEO* variables]
+  		Updates the geo-IP database
 "
 
 
@@ -451,6 +461,7 @@ The required package is called ${APACHE_WSGI_MODPKG}."
     case "`cat /etc/redhat-release`" in
       *"release 5."*)
 	if [ -f /etc/httpd/conf.d/wsgi.conf ]; then
+	  # older el5 epel versions didn't automatically enable it
 	  echo "To enable the module, see instructions in /etc/httpd/conf.d/wsgi.conf"
 	else
 	  echo "The package is in the epel yum repository."
@@ -1597,6 +1608,104 @@ handle_read_only_file_descriptors_on_mount_point() {
 #                                                                              #
 ################################################################################
 
+check_old_dbfile()
+{
+  # only to be used from update_geodb -- depends on some inherited
+  #  local variables
+  if [ -n "`find $dbfile -mtime +"$CVMFS_UPDATEGEO_MAXDAYS"`" ]; then
+    if ! is_root; then
+      echo "Geoip database more than $CVMFS_UPDATEGEO_MAXDAYS days old, do update-geodb as root regularly"
+    elif $lazy; then
+      echo "Geoip database more than $CVMFS_UPDATEGEO_MAXDAYS days old, try update-geodb without -l"
+    else
+      echo "Geoip database more than $CVMFS_UPDATEGEO_MAXDAYS days old, but should never reach this point"
+    fi
+    return 1
+  fi
+}
+
+update_geodb() {
+  local dburl="http://geolite.maxmind.com/download/geoip/database/GeoLiteCity.dat.gz"
+  local dbdir="/var/lib/cvmfs-server/geo"
+  local dbfile=$dbdir/GeoLiteCity.dat
+  local outfile=$dbdir/update.out
+  local lazy=false
+  local retcode=0
+
+  # parameter handling
+  OPTIND=1
+  while getopts "l" option; do
+    case $option in
+      l)
+        lazy=true
+      ;;
+      ?)
+        shift $(($OPTIND-2))
+        usage "Command update-geodb: Unrecognized option: $1"
+      ;;
+    esac
+  done
+
+  # sanity checks
+  is_root || $lazy || die "Only root can update the geo database"
+  [ -d $dbdir ] || die "$dbdir does not exist"
+
+  # check if this is a lazy update and it isn't time to try again yet
+  if $lazy && [ -f $dbfile ] && [ -f $outfile ]; then
+    if [ -z "`find $outfile -mtime +$CVMFS_UPDATEGEO_MINDAYS`" ] || \
+	[ "`date +%w`" -ne "$CVMFS_UPDATEGEO_DAY" ] ||
+	[ "`date +%k`" -lt "$CVMFS_UPDATEGEO_HOUR" ]; then
+      # not time to try again yet
+      # if dbfile is old, warn but don't treat it as an error
+      check_old_dbfile || true
+      return
+    fi
+  fi
+
+  if is_root; then
+    echo "Downloading geoip database"
+    if ! curl -sS --fail --connect-timeout 10 --max-time 60 "$dburl" >$dbfile.gz 2>$outfile; then
+      retcode=1
+    fi
+    cat $outfile
+    if [ $retcode = 0 ]; then
+      if [ -s $dbfile.gz ]; then
+	if zcat $dbfile.gz >$dbfile.new; then
+	  rm -f $dbfile.gz
+	  mv -f $dbfile.new $dbfile
+	else
+	  rm -f $dbfile.gz $dbfile.new
+	  echo "error unzipping geoip database"
+	  $lazy || return 1
+        fi
+      else
+	rm -f $dbfile.gz
+        echo "downloaded geoip database empty"
+	$lazy || return 1
+      fi
+    else
+      rm -f $dbfile.gz
+      echo "error downloading $dburl"
+      $lazy || return 1
+    fi
+  # else not root, can't do the download
+  fi
+
+  if [ ! -f $dbfile ]; then
+    # database has never been downloaded, fatal error
+    is_root || die "Geoip database not downloaded, do update-geodb as root"
+    ! $lazy || die "Geoip database failed to download, do update-geodb without -l"
+    die "Geoip database not downloaded, should never reach this point"
+  fi
+
+  # treat an old dbfile as an error, but not fatal to other cvmfs_server functions
+  check_old_dbfile || return 1
+
+  return
+}
+
+################################################################################
+
 
 alterfs() {
   local master_replica=-1
@@ -1913,6 +2022,10 @@ add_replica() {
       fi
     elif [ $silence_httpd_warning -eq 0 ]; then
       check_wsgi_module
+      update_geodb -l
+      if [ "$cvmfs_user" != root ]; then
+        echo "NOTE: If snapshot is not run regularly as root, do update-geodb monthly from cron"
+      fi
     fi
   fi
   check_upstream_validity $upstream
@@ -1939,8 +2052,8 @@ EOF
 
   if is_local_upstream $upstream; then
     ((echo "# Created by cvmfs_server.  Don't touch."
-      cat_wsgi_config ${name}; cat) | \
-      create_apache_config_file "cvmfs.${name}.conf") << EOF
+      cat_wsgi_config ${alias_name}; cat) | \
+      create_apache_config_file "cvmfs.${alias_name}.conf") << EOF
 # Translation URL to real pathname
 Alias /cvmfs/$alias_name ${storage_dir}
 <Directory "${storage_dir}">
@@ -3188,6 +3301,8 @@ snapshot() {
 	#  if a migrate was done while apache wasn't running, but then
 	#  apache was enabled later
 	check_wsgi_module
+	# try to update the geodb, but continue if it doesn't work
+	update_geodb -l || true
     fi
 
     # do it!
@@ -3398,6 +3513,7 @@ migrate_2_1_15() {
 
   if check_apache; then
     check_wsgi_module
+    update_geodb -l
   fi
   # else apache is currently stopped, add-replica may have been run with -a
 
