check for writable log file directories in chkconfig (#3310)

diff --git a/cvmfs/cvmfs_config b/cvmfs/cvmfs_config
--- a/cvmfs/cvmfs_config
+++ b/cvmfs/cvmfs_config
@@ -374,14 +374,6 @@ cvmfs_chksetup() {
     num_errors=$(($num_errors+1))
   fi
 
-  # Check that if CVMFS_USYSLOG is set, the path is writable.
-  if [ x"$CVMFS_USYSLOG" != x"" ]; then
-    if runascvmfsuser "test -w $(dirname $CVMFS_USYSLOG)"; then
-        echo "Error: $(dirname $CVMFS_USYSLOG) (CVMFS_USYSLOG) is not writable by cvmfs user"
-        num_errors=$(($num_errors+1))
-    fi
-  fi
-
   # Fusermount (not necessary under Mac OS X)
   if [ "$sys_arch" = "Linux" ]; then
     if [ ! -x $fusermount ]; then
@@ -632,6 +624,17 @@ cvmfs_chksetup() {
         echo "Warning: trace mode is on for $fqrn"
         num_warnings=$(($num_warnings+1))
       fi
+
+      # Check that log file directories are writable
+      for parameter in CVMFS_USYSLOG CVMFS_DEBUGLOG CVMFS_TRACEFILE; do
+        eval value=\$$parameter
+        if [ ! -z $value ]; then
+          if ! runascvmfsuser "test -w $(dirname $value)"; then
+            echo "Error: log file directory $parameter=$value not writable for $fqrn"
+            num_errors=$(($num_errors+1))
+          fi
+        fi
+      done
 
       # Check syslog level / facility
       if [ ! -z $CVMFS_SYSLOG_LEVEL ]; then
