check for cvmfs client in mkfs

diff --git a/cvmfs/cvmfs_server b/cvmfs/cvmfs_server
--- a/cvmfs/cvmfs_server
+++ b/cvmfs/cvmfs_server
@@ -233,7 +233,7 @@ snapshot() {
   if [ -f /etc/cvmfs/repositories.d/{$name}/last_snapshot ]; then
     with_history="-p"
   else
-    echo "Initial snaphot"
+    echo "Initial snapshot"
   fi
 
   $user_shell "cvmfs_swissknife pull -m $name \
@@ -302,6 +302,7 @@ mkfs() {
   # Sanity checks
   [ $(id -u) -ne 0 ] && die "Only root can create a new repository"
   /sbin/modprobe aufs || die "aufs kernel module missing"
+  [ -x /usr/bin/cvmfs2 ] || die "cvmfs client missing"
   cat /proc/mounts | grep -q "^/etc/auto.cvmfs /cvmfs " && die "Autofs on /cvmfs has to be disabled"
   [ -d /etc/httpd ] && /sbin/service httpd status >/dev/null || die "Apache must be installed and running"
 
