[cvmfs_config] Issue 3807: abort fuse connections on killall -f(orce)/-s(stuck)
[cvmfs_config] make mountinfo parsing shell agnostic

diff --git a/cvmfs/cvmfs_config b/cvmfs/cvmfs_config
--- a/cvmfs/cvmfs_config
+++ b/cvmfs/cvmfs_config
@@ -99,6 +99,100 @@ var_list="$parm_list $switch_list"
 
 cvmfs_fs_bundle="/Library/Filesystems/cvmfs.fs/Contents/Resources" # Mac OS X
 
+IS_KILLALL_STUCK=FALSE
+IS_KILLALL_FORCE=FALSE
+
+# Check if killall has extra arguments
+# -f(orce): abort all cvmfs associated fuse devices
+# -s(tuck): abort all cvmfs associated fuse devices in waiting state
+parse_killall_opts(){
+  while [[ "${1:-}" == -* ]]; do
+    case "$1" in
+      "-f")
+        IS_KILLALL_FORCE=true
+        ;;
+      "-s")
+        IS_KILLALL_STUCK=true
+        ;;
+      "--help")
+        cvmfs_config_usage
+        ;;
+      *)
+        echo "Ignoring unknown option $1"
+        ;;
+    esac
+    [ $# -gt 0 ] || break
+    shift
+  done
+}
+
+# Given a device id in the form <Major>:<minor>
+# we need only the <minor> part to identify the fuse device
+get_fuse_device()
+{
+  local device_id=$1
+  echo $device_id | cut -d':' -f2
+}
+
+abort_fuse_device(){
+  local fuse_device=$1
+  local device_path="/sys/fs/fuse/connections/$fuse_device"
+  if [ -d "$device_path" ]; then
+    echo -n "Aborting fuse device $fuse_device.. "
+    echo 1 > $device_path/abort
+    echo "OK"
+  fi
+}
+
+# Collect every device associated to a cvmfs mount point,
+# based on /proc/<cvmfs2_pid>/mountinfo
+get_cvmfs_devices()
+{
+  local cvmfs_devices=""
+  for pid in $(pidof "$PROCNAME")
+  do
+    while read -r line; do
+      # Get the interesting fields from every line of mountinfo;
+      # those are the mountpoint and the device id
+      device_id=$(echo "$line" | cut -d' ' -f 3)
+      current_mountpoint=$(echo "$line" | cut -d' ' -f 5)
+
+      if [[ "$current_mountpoint" == "$MOUNTPOINT"/*  ]]; then
+        if ! grep -q "$device_id" <<< "$cvmfs_devices"; then
+          cvmfs_devices=$cvmfs_devices" $device_id"
+        fi
+      fi
+    done < /proc/$pid/mountinfo
+  done
+  echo $cvmfs_devices
+}
+
+abort_all_devices()
+{
+  echo "Aborting all cvmfs fuse devices.."
+  local devices="$@"
+  for device in $devices
+  do
+    abort_fuse_device $(get_fuse_device $device)
+  done
+}
+
+abort_stuck_devices()
+{
+  echo "Aborting stuck cvmfs fuse devices.."
+  local devices="$@"
+  for device in $devices
+  do
+    fuse_dev=$(get_fuse_device $device)
+    local fuse_dev_path="/sys/fs/fuse/connections/$fuse_dev"
+    # Abort waiting devices only
+    if [ "$(cat $fuse_dev_path/waiting)" != "0" ] ;
+    then
+      abort_fuse_device $fuse_dev
+    fi
+  done
+}
+
 # makes sure that a version is always of the form x.y.z-b
 normalize_version() {
   local version_string="$1"
@@ -150,7 +244,7 @@ cvmfs_config_usage() {
   echo "  reload [-c | <repository>]"
   echo "  umount"
   echo "  wipecache"
-  echo "  killall"
+  echo "  killall [-f(orce) ] [-s(tuck)]"
   echo "  bugreport <timeout_in_sec_per_command (default = 90)>"
 }
 
@@ -1386,6 +1480,14 @@ cvmfs_umount() {
 
 cvmfs_killall() {
   local pid=$$
+
+  parse_killall_opts "$@"
+  local cvmfs_devices=$(get_cvmfs_devices)
+  if [ ${IS_KILLALL_FORCE} = true ] ; then
+    abort_all_devices $cvmfs_devices
+  elif [ ${IS_KILLALL_STUCK} = true ] ; then
+    abort_stuck_devices $cvmfs_devices
+  fi
 
   echo -n "Terminating cvmfs_config processes... "
   # The exact match (pgrep -x) works only on Linux.  On macOS, one needs to
