Adding debugging statements and compression classes

diff --git a/cvmfs/cvmfs_server b/cvmfs/cvmfs_server
--- a/cvmfs/cvmfs_server
+++ b/cvmfs/cvmfs_server
@@ -1635,13 +1635,14 @@ sign_manifest() {
   load_repo_config $name
   local user_shell="$(get_user_shell $name)"
 
-  $user_shell "$(__swissknife_cmd) sign \
+  $user_shell "$(__swissknife_cmd dbg) sign \
     -c /etc/cvmfs/keys/${name}.crt      \
     -k /etc/cvmfs/keys/${name}.key      \
     -n $name                            \
     -m $unsigned_manifest               \
     -t ${CVMFS_SPOOL_DIR}/tmp           \
-    -r $CVMFS_UPSTREAM_STORAGE" > /dev/null
+    -r $CVMFS_UPSTREAM_STORAGE" 
+    # >/dev/null
 }
 
 
@@ -2583,7 +2584,7 @@ mkfs() {
     echo -n "(repository flagged volatile)... "
   fi
   local user_shell="$(get_user_shell $name)"
-  local create_cmd="$(__swissknife_cmd) create \
+  local create_cmd="$(__swissknife_cmd dbg) create \
     -t $temp_dir                               \
     -r $upstream                               \
     -a $hash_algo $volatile_opt                \
@@ -2591,7 +2592,8 @@ mkfs() {
   if $garbage_collectable; then
     create_cmd="$create_cmd -z"
   fi
-  $user_shell "$create_cmd" > /dev/null        || die "fail! (cannot init repo)"
+  $user_shell "$create_cmd"      || die "fail! (cannot init repo)"
+  #$user_shell "$create_cmd" > /dev/null        || die "fail! (cannot init repo)"
   sign_manifest $name ${temp_dir}/new_manifest || die "fail! (cannot sign repo)"
   echo "done"
 
@@ -2606,10 +2608,12 @@ mkfs() {
   health_check $name
 
   echo -n "Initial commit... "
-  transaction $name > /dev/null  || die "fail (transaction)"
+  #transaction $name > /dev/null  || die "fail (transaction)"
+  transaction $name || die "fail (transaction)"
   echo "New CernVM-FS repository for $name" > /cvmfs/${name}/new_repository
   chown $cvmfs_user /cvmfs/${name}/new_repository
-  publish $name > /dev/null      || die "fail (publish)"
+  #publish $name > /dev/null      || die "fail (publish)"
+  publish $name      || die "fail (publish)"
   cat $rdonly_dir/new_repository || die "fail (finish)"
 
   print_new_repository_notice $name $cvmfs_user
@@ -3859,7 +3863,7 @@ publish() {
     stratum0=$CVMFS_STRATUM0
     upstream=$CVMFS_UPSTREAM_STORAGE
     hash_algorithm="${CVMFS_HASH_ALGORITHM-sha1}"
-    compression_algo="${CVMFS_COMPRESSION_ALGORITHM-default}"
+    compression_alg="${CVMFS_COMPRESSION_ALGORITHM-default}"
 
     # more sanity checks
     is_owner_or_root $name || { echo "Permission denied: Repository $name is owned by $user"; retcode=1; continue; }
