check /etc/auto.master.d/cvmfs.autofs in chksetup

diff --git a/cvmfs/cvmfs_config b/cvmfs/cvmfs_config
--- a/cvmfs/cvmfs_config
+++ b/cvmfs/cvmfs_config
@@ -352,22 +352,26 @@ cvmfs_chksetup() {
 
   # No autofs integration on OS X
   if [ "$sys_arch" = "Linux" ]; then
-    for path in /etc/auto.master /etc/autofs/auto.master; do
+    for path in /etc/auto.master.d/cvmfs.autofs \
+                /etc/autofs/auto.master.d/cvmfs.autofs \
+                /etc/auto.master \
+                /etc/autofs/auto.master
+    do
       if [ -f $path ]; then
-        AUTOMASTER=$path
+        AUTOFSMAP=$path
         break;
       fi
     done
-    if [ -z "$AUTOMASTER" ]; then
-      echo "Error: unable to find auto.master in any of the supplied paths!"
+    if [ -z "$AUTOFSMAP" ]; then
+      echo "Error: unable to find cvmfs.auto or auto.master in any of the supplied paths!"
       num_errors=$(($num_errors+1))
-      AUTOMASTER=/dev/null
+      AUTOFSMAP=/dev/null
     fi
-    # Check that /etc/auto.cvmfs is referenced in auto.master
+    # Check that /etc/auto.cvmfs is referenced in autofs maps
     # Check that /etc/auto.cvmfs is executable on Linux
-    if ! grep -q "^$CVMFS_MOUNT_DIR[[:space:]]\+\(program:\|\)/etc/auto.cvmfs" $AUTOMASTER 2> /dev/null; then
+    if ! grep -q "^$CVMFS_MOUNT_DIR[[:space:]]\+\(program:\|\)/etc/auto.cvmfs" $AUTOFSMAP 2> /dev/null; then
       if ! check_is_on CVMFS_NFS_SOURCE; then
-        echo "Warning: CernVM-FS map is not referenced from autofs master map"
+        echo "Warning: CernVM-FS map is not referenced from autofs maps ($AUTOFSMAP)"
         num_warnings=$(($num_warnings+1))
       fi
     fi
