Fix: HTTP redirects usage read from the client configuration

diff --git a/cvmfs/cvmfs_server b/cvmfs/cvmfs_server
--- a/cvmfs/cvmfs_server
+++ b/cvmfs/cvmfs_server
@@ -793,12 +793,17 @@ is_master_replica() {
   local name=$1
   local is_master_replica
 
+  load_repo_config $name
+  local swissknife_info_params="-m"
+  if [ x"$CVMFS_FOLLOW_REDIRECTS" == x"yes" ]; then
+    swissknife_info_params="${swissknife_info_params} -L"
+  fi
+
   if [ $(echo $name | cut --bytes=1-7) = "http://" ]; then
-    is_master_replica=$(cvmfs_swissknife info -r $name -m 2>/dev/null)
+    is_master_replica=$(cvmfs_swissknife info -r $name ${swissknife_info_params} 2>/dev/null)
   else
     is_stratum0 $name || return 1
-    load_repo_config $name
-    is_master_replica=$(cvmfs_swissknife info -r $CVMFS_STRATUM0 -m 2>/dev/null)
+    is_master_replica=$(cvmfs_swissknife info -r $CVMFS_STRATUM0 ${swissknife_info_params} 2>/dev/null)
   fi
 
   [ "x$is_master_replica" = "xtrue" ]
@@ -815,7 +820,11 @@ is_garbage_collectable() {
   if is_stratum0 $name; then
     [ x"$CVMFS_GARBAGE_COLLECTION" = x"true" ]
   else
-    [ x"$(cvmfs_swissknife info -r $CVMFS_STRATUM1 -g)" = x"yes" ]
+    local swissknife_info_params="-g"
+    if [ x"$CVMFS_FOLLOW_REDIRECTS" == x"yes" ]; then
+      swissknife_info_params="${swissknife_info_params} -L"
+    fi
+    [ x"$(cvmfs_swissknife info -r $CVMFS_STRATUM1 ${swissknife_info_params})" = x"yes" ]
   fi
 }
 
@@ -1050,13 +1059,20 @@ try_mount_remount_cycle_overlayfs() {
 # download a given file from the backend storage
 # @param noproxy  (optional)
 get_item() {
-  local url="$1"
-  local noproxy="$2"
+  local name="$1"
+  local url="$2"
+  local noproxy="$3"
+
+  load_repo_config $name
+  curl_cmd="curl"
+  if [ x"$CVMFS_FOLLOW_REDIRECTS" == x"yes" ]; then
+    curl_cmd="${curl_cmd} -L"
+  fi
 
   if [ x"$noproxy" != x"" ]; then
-    unset http_proxy && curl -L "$url" 2>/dev/null
+    unset http_proxy && ${curl_cmd} "$url" 2>/dev/null
   else
-    curl "$url" 2>/dev/null
+    ${curl_cmd} "$url" 2>/dev/null
   fi
 }
 
@@ -1485,9 +1501,10 @@ create_whitelist() {
 # @param stratum0  path/URL to stratum0 storage
 # @return          number of seconds until expiry (negativ if already expired)
 get_expiry() {
-  local stratum0=$1
+  local name=$1
+  local stratum0=$2
 
-  local expires=$(get_item $stratum0/.cvmfswhitelist 'noproxy' | head -2 | tail -1 | tail -c15)
+  local expires=$(get_item $name $stratum0/.cvmfswhitelist 'noproxy' | head -2 | tail -1 | tail -c15)
   if echo $expires | grep -q -E --invert-match '^[0-9]{14}$'; then
     echo -1
     return 1
@@ -1512,10 +1529,11 @@ get_expiry() {
 # @param stratum0  path/URL to stratum0 storage
 # @return          0 if whitelist is still valid
 check_expiry() {
-  local stratum0=$1
+  local name=$1
+  local stratum0=$2
   local expiry="-1"
 
-  expiry=$(get_expiry $stratum0)
+  expiry=$(get_expiry $name $stratum0)
   if [ $? -ne 0 ]; then
     echo "Failed to retrieve repository expiry date" >&2
     return 100
@@ -1734,7 +1752,11 @@ get_published_root_hash() {
   local repository_name=$1
 
   load_repo_config $repository_name
-  cvmfs_swissknife info -r $CVMFS_STRATUM0 -c
+  local swissknife_info_params="-c"
+  if [ x"$CVMFS_FOLLOW_REDIRECTS" == x"yes" ]; then
+    swissknife_info_params="${swissknife_info_params} -L"
+  fi
+  cvmfs_swissknife info -r $CVMFS_STRATUM0 ${swissknife_info_params}
 }
 
 
@@ -1893,6 +1915,7 @@ CVMFS_IGNORE_SIGNATURE=no
 CVMFS_AUTO_UPDATE=no
 CVMFS_NFS_SOURCE=no
 CVMFS_HIDE_MAGIC_XATTRS=yes
+CVMFS_FOLLOW_REDIRECTS=yes
 EOF
 }
 
@@ -2543,7 +2566,7 @@ add_replica() {
   public_key=$2
 
   # get the name of the repository pointed to by $stratum0
-  name=$(cvmfs_swissknife info -r $stratum0 -n 2>/dev/null) || die "Failed to access Stratum0 repository at $stratum0"
+  name=$(cvmfs_swissknife info -L -r $stratum0 -n 2>/dev/null) || die "Failed to access Stratum0 repository at $stratum0"
   if [ x$alias_name = x"" ]; then
     alias_name=$name
   else
@@ -3110,7 +3133,7 @@ info() {
   local replication_allowed="yes"
   is_master_replica $name || replication_allowed="no"
   echo "Stratum1 Replication Allowed: $replication_allowed"
-  local expire_countdown=$(get_expiry $stratum0)
+  local expire_countdown=$(get_expiry $name $stratum0)
   if [ $expire_countdown -le 0 ]; then
     echo "Whitelist is expired"
   else
@@ -3259,6 +3282,10 @@ tag() {
   # adds (or moves) a tag in the database
   if [ $action_add -eq 1 ]; then
     local new_manifest="${CVMFS_SPOOL_DIR}/tmp/manifest"
+    local swissknife_tag_create_params=""
+    if [ x"$CVMFS_FOLLOW_REDIRECTS" == x"yes" ]; then
+      swissknife_tag_create_params="${swissknife_tag_create_params} -L"
+    fi
     local tag_create_command="cvmfs_swissknife tag_create \
       -w $CVMFS_STRATUM0                                  \
       -t ${CVMFS_SPOOL_DIR}/tmp                           \
@@ -3269,6 +3296,7 @@ tag() {
       -m $new_manifest                                    \
       -b $base_hash                                       \
       -e $hash_algorithm                                  \
+      $swissknife_tag_create_params                       \
       -a $tag_name"
     if [ ! -z "$add_tag_channel" ]; then
       tag_create_command="$tag_create_command -c $add_tag_channel"
@@ -3444,7 +3472,7 @@ list() {
     local whitelist_info=""
     if is_stratum0 $name; then
       local retval=0
-      check_expiry $CVMFS_STRATUM0 2>/dev/null || retval=$?
+      check_expiry $name $CVMFS_STRATUM0 2>/dev/null || retval=$?
       if [ $retval -eq 100 ]; then
         whitelist_info=" - whitelist unreachable"
       elif [ $retval -ne 0 ]; then
@@ -3513,8 +3541,8 @@ transaction() {
     if [ $force -eq 0 ]; then
       is_in_transaction $name && { echo "Repository $name is already in a transaction"; retcode=1; continue; }
     fi
-    check_expiry $stratum0 || { echo "Repository whitelist for $name is expired!"; retcode=1; continue; }
-    [ $(get_expiry $stratum0) -le $(( 12 * 60 * 60 )) ] && { echo "Warning: Repository whitelist stays valid for less than 12 hours!"; }
+    check_expiry $name $stratum0 || { echo "Repository whitelist for $name is expired!"; retcode=1; continue; }
+    [ $(get_expiry $name $stratum0) -le $(( 12 * 60 * 60 )) ] && { echo "Warning: Repository whitelist stays valid for less than 12 hours!"; }
 
     # do it!
     transaction_before_hook $name
@@ -3692,12 +3720,16 @@ publish() {
     # more sanity checks
     is_owner_or_root $name || { echo "Permission denied: Repository $name is owned by $user"; retcode=1; continue; }
     check_repository_compatibility
-    check_expiry $stratum0         || { echo "Repository whitelist for $name is expired!"; retcode=1; continue; }
+    check_expiry $name $stratum0   || { echo "Repository whitelist for $name is expired!"; retcode=1; continue; }
     is_in_transaction $name        || { echo "Repository $name is not in a transaction"; retcode=1; continue; }
     [ $(count_wr_fds /cvmfs/$name) -eq 0 ] || { echo "Open writable file descriptors on $name"; retcode=1; continue; }
     is_cwd_on_path "/cvmfs/$name" && { echo "Current working directory is in /cvmfs/$name.  Please release, e.g. by 'cd \$HOME'."; retcode=1; continue; } || true
     gc_timespan="$(get_auto_garbage_collection_timespan $name)" || { retcode=1; continue; }
-    local revision_number=$($swissknife info -r $stratum0 -v)
+    local swissknife_info_params="-v"
+    if [ x"$CVMFS_FOLLOW_REDIRECTS" == x"yes" ]; then
+      swissknife_info_params="${swissknife_info_params} -L"
+    fi
+    local revision_number=$($swissknife info -r $stratum0 ${swissknife_info_params})
     if [ x"$manual_revision" != x"" ] && [ $manual_revision -le $revision_number ]; then
       echo "Current revision '$revision_number' is ahead of manual revision number '$manual_revision'."
       retcode=1
@@ -3745,6 +3777,10 @@ publish() {
     local log_level=
     [ "x$CVMFS_LOG_LEVEL" != x ] && log_level="-z $CVMFS_LOG_LEVEL"
 
+    local swissknife_sync_params=""
+    if [ x"$CVMFS_FOLLOW_REDIRECTS" == x"yes" ]; then
+      swissknife_sync_params="${swissknife_sync_params} -L"
+    fi
     local sync_command="$swissknife sync $verbosity -u /cvmfs/$name \
       -s ${spool_dir}/scratch \
       -c ${spool_dir}/rdonly \
@@ -3754,6 +3790,7 @@ publish() {
       -w $stratum0 \
       -o $manifest \
       -e $hash_algorithm \
+      $swissknife_sync_params \
       $log_level $tweaks_option"
     if [ "x$CVMFS_UNION_FS_TYPE" != "x" ]; then
       sync_command="$sync_command -f $CVMFS_UNION_FS_TYPE"
@@ -3782,6 +3819,10 @@ publish() {
     if [ "x$CVMFS_MAXIMAL_CONCURRENT_WRITES" != "x" ]; then
       sync_command="$sync_command -q $CVMFS_MAXIMAL_CONCURRENT_WRITES"
     fi
+    local swissknife_tag_create_params=""
+    if [ x"$CVMFS_FOLLOW_REDIRECTS" == x"yes" ]; then
+      swissknife_tag_create_params="${swissknife_tag_create_params} -L"
+    fi
     local tag_command="$swissknife tag_create \
       -r $upstream                            \
       -w $stratum0                            \
@@ -3791,6 +3832,7 @@ publish() {
       -f $name                                \
       -b $base_hash                           \
       -e $hash_algorithm                      \
+      $swissknife_tag_create_params           \
       -x" # -x enables magic undo tag handling
     if [ ! -z "$tag_name" ]; then
       tag_command="$tag_command -a $tag_name"
@@ -3915,7 +3957,7 @@ rollback() {
   # more sanity checks
   is_owner_or_root $name || die "Permission denied: Repository $name is owned by $user"
   check_repository_compatibility
-  check_expiry $stratum0  || die "Repository whitelist is expired!"
+  check_expiry $name $stratum0  || die "Repository whitelist is expired!"
   is_in_transaction $name && die "Cannot rollback a repository in a transaction"
   is_cwd_on_path "/cvmfs/$name" && die "Current working directory is in /cvmfs/$name.  Please release, e.g. by 'cd \$HOME'." || true
 
@@ -4073,7 +4115,11 @@ gc() {
     is_owner_or_root       $name || die "Permission denied: Repository $name is owned by $user"
     is_in_transaction      $name && die "Cannot run garbage collection while in a transaction"
 
-    local head_timestamp="$(cvmfs_swissknife info -r $CVMFS_STRATUM0 -t)"
+    local swissknife_info_params="-t"
+    if [ x"$CVMFS_FOLLOW_REDIRECTS" == x"yes" ]; then
+      swissknife_info_params="${swissknife_info_params} -L"
+    fi
+    local head_timestamp="$(cvmfs_swissknife info -r $CVMFS_STRATUM0 ${swissknife_info_params})"
     [ $head_timestamp -gt $preserve_timestamp ] || die "Latest repository revision is older than given timestamp"
 
     # figure out the URL of the repository
