Add dcoredumper to CMake & cvmfs_config

diff --git a/cvmfs/cvmfs_config b/cvmfs/cvmfs_config
--- a/cvmfs/cvmfs_config
+++ b/cvmfs/cvmfs_config
@@ -288,7 +288,7 @@ cvmfs_config_usage() {
   echo ""
   echo "  bugreport [timeout_in_sec_per_command (default = 90)]"
   echo ""
-  echo "  dcoredump [<pid> <output.core> | <output.core>]"
+  echo "  dcoredump <pid> [output.core]"
 }
 
 has_selinux() {
@@ -1793,6 +1793,30 @@ cvmfs_bugreport() {
 }
 
 
+cvmfs_dcoredump() {
+  local dumper_bin="${INSTALL_BASE}/bin/dcoredumper"
+  if [ ! -x "$dumper_bin" ]; then
+    echo "Error: dcoredumper binary not found at $dumper_bin"
+    return 1
+  fi
+
+  if [ $# -lt 1 ]; then
+    echo "Usage: cvmfs_config dcoredump <pid> [output.core]"
+    return 1
+  fi
+
+  local pid=$1
+  local outfile=$2
+  if [ -z "$outfile" ]; then
+    outfile="/tmp/cvmfs_dcoredump_${pid}_$(date +%Y%m%d_%H%M%S).core"
+  fi
+
+  echo "Dumping core for PID $pid to $outfile"
+  $dumper_bin $pid "$outfile"
+  return $?
+}
+
+
 die() {
   echo -e $1 >&2
   exit 1
@@ -2710,6 +2734,16 @@ case "$1" in
      fi
      shift 1
      cvmfs_bugreport $@
+     RETVAL=$?
+     ;;
+
+   dcoredump)
+     if [ `id -u` -ne 0 ]; then
+       echo "root privileges required"
+       exit 1
+     fi
+     shift 1
+     cvmfs_dcoredump $@
      RETVAL=$?
      ;;
 
