fix nouser option for cvmfs_config

diff --git a/cvmfs/cvmfs_config b/cvmfs/cvmfs_config
--- a/cvmfs/cvmfs_config
+++ b/cvmfs/cvmfs_config
@@ -229,6 +229,8 @@ cvmfs_setup() {
   done
 
   mkdir -p /cvmfs
+  # set permissions for home dir
+  mkdir -p /var/lib/cvmfs
 
   if [ $nouser -eq 0 ]; then
     if ! check_group "cvmfs"; then
@@ -244,11 +246,9 @@ cvmfs_setup() {
         exit 1
       fi
     fi
+    chown cvmfs:cvmfs /var/lib/cvmfs
   fi
 
-  # set permissions for home dir
-  mkdir -p /var/lib/cvmfs
-  chown cvmfs:cvmfs /var/lib/cvmfs
 
   # put workarounds for OS X in place (CernVM-FS poor-man's relocatability)
   if [ x"$sys_arch" = x"Darwin" ]; then
@@ -279,11 +279,13 @@ cvmfs_setup() {
     fi
   fi
 
-  # if group fuse exists, add user cvmfs
-  if check_group "fuse"; then
-    if ! add_user_to_group_fuse; then
-      echo "Cannot add user cvmfs to group fuse"
-      exit 1
+  if [ $nouser -eq 0 ]; then
+    # if group fuse exists, add user cvmfs
+    if check_group "fuse"; then
+      if ! add_user_to_group_fuse; then
+        echo "Cannot add user cvmfs to group fuse"
+        exit 1
+      fi
     fi
   fi
 
