Second draft of server-side support.
- Fix bash var names in cvmfs_server.  Don't try to read from external
  repo when creating a new filesystem.
- Allows the .cvmfscatalog file to either be manipulated through xattrs
  or key=val pairs in the file itself.
- Distinguish between unset and disabled property.
  (improves hierarchy support; unset means 'inherit from parent' while
   disable means to override parent.)

diff --git a/cvmfs/cvmfs_server b/cvmfs/cvmfs_server
--- a/cvmfs/cvmfs_server
+++ b/cvmfs/cvmfs_server
@@ -2416,14 +2416,14 @@ mkfs() {
   local garbage_collectable=false
   local s3_config=""
   local keys_import_location
-  local external=0
+  local external_data=0
 
   # parameter handling
   OPTIND=1
   while getopts "Xw:u:o:mf:vga:zs:k:" option; do
     case $option in
       X)
-        external=1
+        external_data=1
       ;;
       w)
         stratum0=$OPTARG
@@ -2611,7 +2611,12 @@ mkfs() {
   echo "New CernVM-FS repository for $name" > /cvmfs/${name}/new_repository
   chown $cvmfs_user /cvmfs/${name}/new_repository
   publish $name > /dev/null      || die "fail (publish)"
-  cat $rdonly_dir/new_repository || die "fail (finish)"
+  # When publishing an external repository, it is the user's responsibility to
+  # stage the actual data files to the web server - not the publication function.
+  # Hence, the following is guaranteed to not work.
+  if [ external_data -eq 0 ]; then
+    cat $rdonly_dir/new_repository || die "fail (finish)"
+  fi
 
   print_new_repository_notice $name $cvmfs_user
 }
