FIX: chown must run as root

diff --git a/cvmfs/cvmfs_server b/cvmfs/cvmfs_server
--- a/cvmfs/cvmfs_server
+++ b/cvmfs/cvmfs_server
@@ -4674,18 +4674,18 @@ catalog_chown() {
 
   local tmp_dir=${CVMFS_SPOOL_DIR}/tmp
   local manifest=${tmp_dir}/manifest
-  cvmfs_swissknife migrate     \
-    -v "chown"                 \
-    -r $CVMFS_STRATUM0         \
-    -n $name                   \
-    -u $CVMFS_UPSTREAM_STORAGE \
-    -t $tmp_dir                \
-    -k $CVMFS_PUBLIC_KEY       \
-    -o $manifest               \
-    -i $uid_map                \
-    -j $gid_map                \
-    -s || die "fail"
-
+  local migrate_command="$(__swissknife_cmd dbg) migrate     \
+                              -v 'chown'                     \
+                              -r $CVMFS_STRATUM0             \
+                              -n $name                       \
+                              -u $CVMFS_UPSTREAM_STORAGE     \
+                              -t $tmp_dir                    \
+                              -k $CVMFS_PUBLIC_KEY           \
+                              -o $manifest                   \
+                              -i $uid_map                    \
+                              -j $gid_map                    \
+                              -s"
+  sh -c "$migrate_command" || die "Fail (executed command: $migrate_command)"
   local trunk_hash=$(grep "^C" $manifest | tr -d C)
 
   # finalizing transaction
@@ -4694,11 +4694,9 @@ catalog_chown() {
 
   # committing newly created revision
   echo "Signing new manifest"
-  sign_manifest $name $manifest      || { publish_failed $name; die "Signing failed"; }
-  set_ro_root_hash $name $trunk_hash || { publish_failed $name; die "Root hash update failed"; }
-
-  # remount the repository
-  close_transaction $name
+  chown $CVMFS_USER $manifest        || die "chmod of new manifest failed";
+  sign_manifest $name $manifest      || die "Signing failed";
+  set_ro_root_hash $name $trunk_hash || die "Root hash update failed";
 
   return
 }
