minor compatibility fixes in cvmfs_config

diff --git a/cvmfs/cvmfs_config b/cvmfs/cvmfs_config
--- a/cvmfs/cvmfs_config
+++ b/cvmfs/cvmfs_config
@@ -229,7 +229,11 @@ cvmfs_chksetup() {
   if [ "$sys_arch" = "Darwin" ]; then
     tools="/sbin/mount_cvmfs"
   elif [ "$sys_arch" = "Linux" ]; then
-    tools="/sbin/mount.cvmfs"
+    if [ -d /sbin ]; then
+      tools="/sbin/mount.cvmfs"
+    else
+      tools="/usr/bin/mount.cvmfs"
+    fi
   fi
 
   local tool
@@ -1397,6 +1401,36 @@ activate_service() {
 }
 
 
+reload_service() {
+  local svc=$1
+
+  case $sys_arch in
+    Linux )
+      if [ -e /usr/bin/systemctl ]; then
+        /usr/bin/systemctl reload -q ${svc}.service
+      elif [ -e /sbin/service -o -e /usr/sbin/service ]; then
+        local servicebin=/sbin/service
+        if [ ! -e $servicebin ]; then
+          servicebin=/usr/sbin/service
+        fi
+        $servicebin $svc reload >/dev/null 2>&1
+      else
+        echo "Utility to manage services missing"
+        exit 1
+      fi
+    ;;
+    Darwin )
+      # Not supported at this point
+      :
+    ;;
+    * )
+      echo "Architecture $sys_arch is not supported"
+      exit 1
+    ;;
+  esac
+}
+
+
 configure_autofs() {
   case $sys_arch in
     Linux )
@@ -1404,7 +1438,7 @@ configure_autofs() {
       local cvmfs_map="$CVMFS_MOUNT_DIR /etc/auto.cvmfs"
       if ! grep -q "^$cvmfs_map" /etc/auto.master; then
         echo "$cvmfs_map" >> /etc/auto.master
-        $pidof automount > /dev/null && $service autofs reload > /dev/null || true
+        $pidof automount > /dev/null && reload_service autofs || true
       fi ;;
 
    Darwin )
