spooler interface (work in progress)

diff --git a/cvmfs/cvmfs_server b/cvmfs/cvmfs_server
--- a/cvmfs/cvmfs_server
+++ b/cvmfs/cvmfs_server
@@ -195,31 +195,35 @@ publish() {
   sudo /bin/mount -o remount,ro /cvmfs/$name
   local base_hash=$(attr -qg root_hash ${spool_dir}/rdonly)
    
-  $user_shell "cvmfs_sync -p -u /cvmfs/$name \
+  
+  $user_shell "cvmfs_sync -x -u /cvmfs/$name \
     -s ${spool_dir}/scratch \
     -c ${spool_dir}/rdonly \
     -t ${spool_dir}/tmp \
     -b $base_hash \
-    -x ${spool_dir}/paths \
-    -y ${spool_dir}/digests \
+    -p ${spool_dir}/paths \
+    -d ${spool_dir}/digests \
+    -l $repository_dir \
     -w $stratum0 \
-    -o ${spool_dir}/tmp/manifest" || die "Synchronization failed"
-  #$user_shell "cvmfs_sign \
-  #  -c /etc/cvmfs/keys/${name}.crt \
-  #  -k /etc/cvmfs/keys/${name}.key \
-  #  -n $name \
-  #  -t ${spool_dir}/tmp \
-  #  -r $upstream \
-  #  -m ${spool_dir}/tmp/manifest" || die "Signing failed"
-  #sudo umount /cvmfs/$name
-  #sudo umount ${spool_dir}/rdonly
-  #sudo rm -rf ${spool_dir}/scratch
-  #rm -rf ${spool_dir}/tmp/*
-  #$user_shell "mkdir ${spool_dir}/scratch"
-  #sudo mount ${spool_dir}/rdonly > /dev/null
-  #sudo mount /cvmfs/$name
-  #rm -f ${spool_dir}/in_transaction
-  #publish_after_hook $name
+    -o ${temp_dir}/new_manifest" || die "Synchronization failed"
+  $user_shell "cvmfs_sign -c /etc/cvmfs/keys/${name}.crt \
+    -k /etc/cvmfs/keys/${name}.key \
+    -n $name \
+    -m ${spool_dir}/tmp/manifest \
+    -t ${spool_dir}/tmp \
+    -p ${spool_dir}/paths \
+    -d ${spool_dir}/digests \
+    -l $repository_dir" || die "Signing failed"
+  echo "Remounting newly created repository revision"
+  sudo umount /cvmfs/$name
+  sudo umount ${spool_dir}/rdonly
+  sudo rm -rf ${spool_dir}/scratch
+  rm -rf ${spool_dir}/tmp/*
+  $user_shell "mkdir ${spool_dir}/scratch"
+  sudo mount ${spool_dir}/rdonly > /dev/null
+  sudo mount /cvmfs/$name
+  rm -f ${spool_dir}/in_transaction
+  publish_after_hook $name
 }
 
 
@@ -381,10 +385,6 @@ EOF
     -l $repository_dir" > /dev/null
   echo "done"
   
-  echo -n "Waiting for inital repository to become available on Stratum 0..."
-  # TODO
-  echo "done"
-
   echo -n "Mounting CernVM-FS Storage... "
   cat >> /etc/fstab << EOF
 $name $rdonly_dir cvmfs no_reload 0 0 # added by CernVM-FS for $name
@@ -394,12 +394,11 @@ EOF
   mount /cvmfs/$name
   echo "done"
 
-  echo -n "Starting services... "
-  #transaction $name $spool_dir > /dev/null
-  #echo "New CernVM-FS repository for $name" > /cvmfs/${name}/new_repository
-  #CVMFS_PUBLISH_OPTIONS="-z"
-  #publish $name $cvmfs_user $spool_dir $stratum0 $upstream
-  #cat $rdonly_dir/new_repository
+  echo -n "Initial commit... "
+  transaction $name $spool_dir > /dev/null
+  echo "New CernVM-FS repository for $name" > /cvmfs/${name}/new_repository
+  publish $name $cvmfs_user $spool_dir $stratum0 $upstream
+  cat $rdonly_dir/new_repository
 
   echo "\
 
