Refactor: DRY up then check for many backend items

diff --git a/cvmfs/cvmfs_server b/cvmfs/cvmfs_server
--- a/cvmfs/cvmfs_server
+++ b/cvmfs/cvmfs_server
@@ -2960,17 +2960,18 @@ import() {
 
   # investigate the given repository storage for sanity
   local storage_location=$(get_upstream_config $upstream)
-  [ -d $storage_location ] || die "Did not find repository storage to import at $storage_location"
-  [ -f "${storage_location}/.cvmfspublished" ] || die "${storage_location}/.cvmfspublished missing"
-  [ -d "${storage_location}/data"     ] || die "${storage_location}/data missing"
-  [ -d "${storage_location}/data/txn" ] || die "${storage_location}/data/txn missing"
-  i=0
+  local needed_items="${storage_location}                 \
+                      ${storage_location}/.cvmfspublished \
+                      ${storage_location}/data            \
+                      ${storage_location}/data/txn"
+  local i=0
   while [ $i -lt 256 ]; do
-    subdir=$(printf "%02x" $i)
-    [ -d ${storage_location}/data/${subdir} ] || die "${storage_location}/data/XX incomplete [XX = $subdir]"
+    needed_items="$needed_items ${storage_location}/data/$(printf "%02x" $i)"
     i=$(($i+1))
   done
-  echo "done"
+  for item in $needed_items; do
+    [ -e $item ] || die "$item missing"
+  done
 
   if [ $recreate_whitelist -eq 0 ]; then
     [ -f "${storage_location}/.cvmfswhitelist" ] || die "didn't find ${storage_location}/.cvmfswhitelist"
