FIX: check sanity of repository's storage backend

diff --git a/cvmfs/cvmfs_server b/cvmfs/cvmfs_server
--- a/cvmfs/cvmfs_server
+++ b/cvmfs/cvmfs_server
@@ -3016,6 +3016,19 @@ import() {
     echo "done"
   fi
 
+  # check imported storage location
+  echo -n "Sanity-Checking imported CernVM-FS storage... "
+  [ -d ${storage_location}/data     ] || die "fail! (${storage_location}/data missing)"
+  [ -d ${storage_location}/data/txn ] || die "fail! (${storage_location}/data/txn missing)"
+  i=0
+  while [ $i -lt 256 ]; do
+    subdir=$(printf "%02x" $i)
+    [ -d ${storage_location}/data/${subdir} ] || die "fail! (${storage_location}/data/XX incomplete [XX = $subdir])"
+    i=$(($i+1))
+  done
+  [ -f ${storage_location}/.cvmfspublished ] || die "fail! (${storage_location}/.cvmfspublished missing)"
+  echo "done"
+
   # recreate whitelist if requested
   if [ $recreate_whitelist -ne 0 ]; then
     echo -n "Recreating whitelist... "
