Refactor: factor out import_keychain() from import()

diff --git a/cvmfs/cvmfs_server b/cvmfs/cvmfs_server
--- a/cvmfs/cvmfs_server
+++ b/cvmfs/cvmfs_server
@@ -1483,6 +1483,30 @@ remove_spool_area() {
 }
 
 
+import_keychain() {
+  local name=$1
+  local keys_location="$2"
+  local cvmfs_user=$3
+  local keys="$4"
+
+  local global_key_dir="/etc/cvmfs/keys"
+  mkdir -p $global_key_dir || return 1
+  for keyfile in $keys; do
+    echo -n "importing $keyfile ... "
+    if [ ! -f "${global_key_dir}/${keyfile}" ]; then
+      cp "${keys_location}/${keyfile}" $global_key_dir || return 2
+    fi
+    local key_mode=444
+    if echo "$keyfile" | grep -q '.*key$'; then
+      key_mode=400
+    fi
+    chmod $key_mode "${global_key_dir}/${keyfile}"   || return 3
+    chown $cvmfs_user "${global_key_dir}/${keyfile}" || return 4
+    echo "done"
+  done
+}
+
+
 create_repository_storage() {
   local name=$1
   local storage_dir
@@ -2192,12 +2216,6 @@ import() {
   [ x"$stratum0" = x ] && stratum0="http://localhost/cvmfs/$name"
   [ x"$upstream" = x ] && upstream=$(make_upstream "local" "/srv/cvmfs/$name/data/txn" "/srv/cvmfs/$name")
 
-  # security key pathes
-  local private_key="${name}.key"
-  local certificate="${name}.crt"
-  local public_key="${name}.pub"
-  local pki_keys="$private_key $certificate $public_key"
-
   # sanity checks
   check_repository_existence $name  && die "The repository $name already exists"
   is_root                           || die "Only root can create a new repository"
@@ -2210,9 +2228,6 @@ import() {
   is_local_upstream $upstream       || die "Import only works locally for the moment"
   lower_hardlink_restrictions
   ensure_enabled_apache_modules
-  for pki_file in $pki_keys; do
-    [ -f "${keys_location}/$pki_file" ] || die "Cannot find $pki_file in $keys_location"
-  done
   [ x"$keys_location" = "x" ] && die "Please provide the location of the repository security keys (-k)"
 
   # investigate the given repository storage for sanity
@@ -2241,15 +2256,11 @@ import() {
 
   # import the old repository security keys
   echo -n "Importing the given key files... "
-  local global_key_dir="/etc/cvmfs/keys"
-  mkdir -p $global_key_dir || die "fail! (cannot create $global_key_dir)"
-  for pki_file in $pki_keys; do
-    if [ ! -f "${global_key_dir}/$pki_file" ]; then
-      cp "${keys_location}/$pki_file" $global_key_dir  || die "fail! (cannot copy $pki_file)"
-    fi
-    chmod 444 "${global_key_dir}/${pki_file}"          || die "fail! (cannot chmod $pki_file)"
-    chown $cvmfs_user "${global_key_dir}/${pki_file}"  || die "fail! (cannot chown $pki_file)"
-  done
+  local private_key="${name}.key"
+  local certificate="${name}.crt"
+  local public_key="${name}.pub"
+  keys="$private_key $certificate $public_key"
+  import_keychain $name "$keys_location" $cvmfs_user "$keys" > /dev/null || die "fail!"
   echo "done"
 
   # create storage
@@ -2289,7 +2300,7 @@ import() {
       -n $name \
       -u $upstream \
       -t $temp_dir \
-      -k "${global_key_dir}/$public_key" \
+      -k "/etc/cvmfs/keys/$public_key" \
       -o $new_manifest \
       -p $cvmfs_uid \
       -g $cvmfs_gid \
@@ -2300,8 +2311,8 @@ import() {
     # sign new (migrated) repository revision
     echo -n "Signing newly imported Repository... "
     sudo -H -u $cvmfs_user sh -c "cvmfs_swissknife sign \
-      -c ${global_key_dir}/${certificate} \
-      -k ${global_key_dir}/${private_key} \
+      -c /etc/cvmfs/keys/${certificate} \
+      -k /etc/cvmfs/keys/${private_key} \
       -n $name \
       -m $new_manifest \
       -t $temp_dir \
