report failure in CI if any one of the tests failed

diff --git a/.github/workflows/ci_vng.yaml b/.github/workflows/ci_vng.yaml
--- a/.github/workflows/ci_vng.yaml
+++ b/.github/workflows/ci_vng.yaml
@@ -239,6 +239,12 @@ jobs:
                     --                                             \
                    "${CVMFS_TESTCASES}"
 
+          EXIT_CODE=$(cat results/tests_status)
+          if [ "$EXIT_CODE" -ne 0 ]; then
+              echo "Some tests failed."
+              exit 1
+          fi
+
       - name: Upload results
         if: always()
         uses: actions/upload-artifact@v4
